### ISSUE TITLE
can openpose process multi images at one time

### ISSUE THREAD

**Issue by mxmxlwlw** [CMU-Perceptual-Computing-Lab/openpose#100]
If can't what should I do

**Comment by gineshidalgo99** [comment]
### Posting rules
2. **No** posts about **questions already answered / clearly explained in** the **documentation**

**Comment by mxmxlwlw** [comment]
No, I want to process many image AT ONE TIME, not process them constantly...

**Comment by gineshidalgo99** [comment]
Sorry for the confusion! What do you mean by at one time? I do not fully understand it.

**Comment by mxmxlwlw** [comment]
@gineshidalgo99 I mean that I can process many Images simultaneously so that if my gpu is good enough, I can save a lot of time.

**Comment by gineshidalgo99** [comment]
No, there is no such functionality already done, so far you will have to use the `--image_dir` flag.

You could use the wrapper tutorial, and as custom producer, put a vector of images instead of a single image, that will be closer to your purposes, since it will apply successively the deep net to all the images on that vector before doing the rest of the processing.

Or with the same tutorial wrapper, you could manually merge all the images in a same huge image (and increase proportionally the `net_resolution`), but why would this save a lot of time? It might save something, but I am not that sure it will save that much time to be useful. (I might be wrong)

**Comment by mxmxlwlw** [comment]
@gineshidalgo99  I don't know. I already modified your code. So it can process multi images. And I tested the speed. It seems much time is comsumed by the network. However I found that batching can not help to speed up using caffe. And that's too shame... Can you explain that?

**Comment by gineshidalgo99** [comment]
My understanding and limited experience is that batching help converging, and that is why it speed up training. But each iteration takes so much longer, i.e. the bigger the batch size, the longer the net needs per image or sample. So I'd say that for testing, in order to make batch size efficient, it should just be performed one by one. If someone disagrees please correct me, I might be wrong.

**Comment by lliuz** [comment]
@gineshidalgo99, @mxmxlwlw , I have the same idea as you discussed that I want to speed up the time spent on each image by batch inference.
Do you have any follow-up attempts? I think batch inference is more efficient than one by one and I have verified it on the rtpose pytorch version. I'm curious why not same on Caffe..

**Comment by mxmxlwlw** [comment]
@lliuz Yeah... It can speed up, however it really depends on your resources and your size of the net. If your network is too big, you will get very little improvements. But if your network is small, it will benefits. Because the transition of your data and the use of your GPU will be better!

**Comment by filipetrocadoferreira** [comment]
Any plans on this issue? Batch inference will reduce a lot /per_image inference time

**Comment by gineshidalgo99** [comment]
I did some quick test, the increase in GPU memory required is 3x (for 3 images), going to ~4GB, while the speed up was < 10%, so I might eventually implement it properly, but right now it's not at the top of my priority list given the trade off and small gain.
