### ISSUE TITLE
Openpose build for Unity

### ISSUE THREAD

**Issue by pavchavan** [CMU-Perceptual-Computing-Lab/openpose#1071]
latest pull ,not able to build the openpose using USE_UNITY_SUPPORT .

getting the error "Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'op::WrapperStructPose::WrapperStructPose(op::WrapperStructPose &&)': cannot convert argument 1 from 'bool' to 'const op::PoseMode' (compiling source file D:\Work\VisualStudioMainWorks\OpenPose_Main_git\src\openpose\unity\unityBinding.cpp)	openpose	C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory	901	
"

on commit de117486e1e6ba29960bae50ebe1348be38264d9

**Comment by gineshidalgo99** [comment]
Fixed in the last commit. PLease, try again and let me know the result.

But, I would not try to use non-official versions yet.  Every time we add new functionality that requires a new flag (provoking this code to crash), it means that the official Unity code will not work without modifications too. That's why we recommend using the Unity recommended version always.
