### ISSUE TITLE
How to configure on Windows 10 to get the accuracy of your paper

### ISSUE THREAD

**Issue by gdcyk** [CMU-Perceptual-Computing-Lab/openpose#1112]
Dear Sir/Madame,
    I use the openpose with the Maximum Accuracy Configuration posted on openpose/doc/quick_start.md to test the COCO test2017-dev, but I didn't get the same results as your paper.

And the configuration is (on Windows):
    bin\OpenPoseDemo.exe --net_resolution "1312x736" --scale_number 4 --scale_gap 0.25
    pose_iter_584000.caffemodel

    How set the configuration on window10 to get the accuracy of your paper

**Comment by gineshidalgo99** [comment]
I will update the doc with the following (that answers your question):

If you want to increase the accuracy value metric on COCO, while harming the qualitative accuracy, add the flag `--maximize_positives`. It reduces the thresholds to accept a person candidate. It highly increases both false and true positives. I.e., it maximizes average recall but could harm average precision. Our experience is that it looks much worse visually, but it improves the COCO accuracy numbers, so use it at your own risk.

In addition, our paper numbers are not based on the current models that have been released. We released our best model at the time but later found a better one. But given that the accuracy difference is less than 2%, we did not want to release yet another model to avoid confusion for the users (otherwise there would be more than 10 models released at this point). We will release a new one every time a major improvement is achieved.
