### ISSUE TITLE
I successfully ran build/examples/openpose/openpose.bin . but failed to run 01_body_from_image.py .any one can help me?

### ISSUE THREAD

**Issue by DragonAndSky** [CMU-Perceptual-Computing-Lab/openpose#1163]
### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.
  python3 01_body_from_image.py 

### Errors (if any)
ERROR: something wrong with flag 'flagfile' in file  '/pose_estimator/gflags/src/gflags.cc' One possibility: '/pose_estimator/gflags/src/gflags.cc'  is being linked both statically and dynamically into this executable.

### Type of Issue
- Execution error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code

3. **General configuration**:
    - **Installation mode**:(Ubuntu); CMake-gui
    - **Operating system** (Ubuntu):Ubuntu
    - **Operating system version** (Ubuntu 16):Ubuntu 16.04
    - **Release or Debug mode**? (release):release
    - Compiler (`gcc --version` in Ubuntu ): 5.4.0

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (no):
    - Any other custom CMake configuration with respect to the default version? ( no):

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** (`cmake --version` in Ubuntu): 3.5.1
    - **OpenCV version**: apt-get install libopencv-dev` (only Ubuntu)

6. If **GPU mode** issue:
    - **CUDA version** ( 9.2.148):
    - **cuDNN version**: 7.5.0
    - **GPU model** (`nvidia-smi` in Ubuntu):
| NVIDIA-SMI 418.39       Driver Version: 418.39       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0  On |                  N/A |
| 47%   27C    P8    16W / 250W |    789MiB / 11175MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+

8. If **Python** API:
    - **Python version**: 3.5
    - **Numpy version**:1.14

**Comment by HaxiSnake** [comment]
Me too ...

**Comment by HaxiSnake** [comment]
Hi, I have fixed this problem.
It is caused by  using the dynamic glog library and the static gflags library to complie caffe or openpose.
Like [this](https://github.com/google/glog/issues/53) described.
So you need to rebuild gflags to get the dynamic gflags library.
eg:
`cd GFLAGS_SRC_DIR`
`mkdir build`
`cd build`
`cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_SHARED_LIBS=ON ..`
`make`
`sudo make install`
`sudo ldconfig `
Then you can change the CmakeCache.txt manually as below:
origin:
` GFLAGS_LIBRARY:FILEPATH=/usr/local/lib/libgflags.a `
after change:
` GFLAGS_LIBRARY:FILEPATH=/usr/local/lib/libgflags.so `
then make clean and rebuild
maybe it works for you.

**Comment by gineshidalgo99** [comment]
Thanks for the solution!
