### ISSUE TITLE
Maximum accuracy configuration on lower end GPUs possible?

### ISSUE THREAD

**Issue by AndroXD** [CMU-Perceptual-Computing-Lab/openpose#1211]
I've read that this command provides the most accurate results possible on Openpose so far: https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/quick_start.md#maximum-accuracy-configuration
However, my measly GTX 1070 will run out of memory (only 8GB) if I do that, is there any method to achieve the same accuracy on GPU using less memory even if it meant sacrificing speed?
I'm trying to track complex movements (ie. breakdancers, martial artists, parkours, etc.) and get lots of skipped frames/errors, so it's important that I can squeeze as much accuracy as possible.
Any help is much appreciated, thanks!

**Comment by gineshidalgo99** [comment]
Unfortunately no, there is no way. Caffe just takes so much memory doing that. You can try with only scale_number 3 instead of 4, reducing a bit the resolution (e.g. 720 vs. default 736) and starting the computer without GUI (which also takes about 1GB of memory just to keep the computer GUI running).
