### ISSUE TITLE
Overhead of op::Wrapper

### ISSUE THREAD

**Issue by ChrizzyM87** [CMU-Perceptual-Computing-Lab/openpose#1237]
I would like to know if anybody did some benchmarks regarding the overhead of op::Wrapper, especially with multithreading disabled.

Background is that I do want to extract body pose and facial landmarks as fast as possible for a real time application. I thought that it might be a good idea to use the wrapper, because I expect that data exchange and stuff like that between PoseExtractor and FaceExtractor is handled fine.
If I wouldn't use the wrapper I had to manually call PoseExtractor first, pass the image, and than pass face ROIs and the image again to the FaceExtractor.

Is my expectation correct that the solution which is implemented in the wrapper is better and does not e.G. pass the image twice to the GPU?

**Comment by gineshidalgo99** [comment]
The overhead is almost 0 compared to running the OpenPose network, it doesn't affect the FPS.

About sharing memory, no it does not share it. PoseExtractor uses all the image, while the FaceExtractor resizes the crop of the face image and resizes it up. So sharing would not be direct and it would require additionally storing the original image into GPU as well and then applying the crops from there.
You are right, it is possible and it would speed it up a bit but multiple people, but it requires some extra work and it will not speedup images with 1-2 people, because we would be loading the whole image into GPU memory only to use a crop of it. So I did not implement it nor test it. Feel free (you or anyone) to do a PR if you implement a working version.
