### ISSUE TITLE
Real time keypoints data

### ISSUE THREAD

**Issue by DarcyWL** [CMU-Perceptual-Computing-Lab/openpose#125]
Hi!
Right now I have checked at `openpose-windows\windows_project\TutorialWrapper` and I am able to extract keypoints of pictures from given directory.
However, I wonder how to extract real-time keypoint data from webcam. As you have done in the OpenPoseDemo, where real-time keypoint data can be stored.  Before you stored the data into .xml(or other formats), you must have a variable storing keypoints, right? 
I have checked the code for OpenPoseDemo, and I found that the keypoints were stored by the following command:

> opWrapper.configure(wrapperStructPose, wrapperStructFace, wrapperStructHand, wrapperStructInput, wrapperStructOutput);

Could you please help me extract real-time Keypoints data from webcam?  
Thank you!!

**Comment by DarcyWL** [comment]
Also, I have another question.
This is what I put into the UserOutPutClass in `openpose-windows\windows_project\TutorialWrapper\1_user_asynchronous.cpp`
![tukgf_6h 5v5 q yrsixi](https://user-images.githubusercontent.com/29938309/27898060-a60fb4da-6256-11e7-82e4-3bbbef41a212.png)
Everything works fine.
However, if I write my own codes like this(basically, I want to store interested pose into a float array)
![_oxd g h x0 _bvsx vo2](https://user-images.githubusercontent.com/29938309/27898077-bea9c198-6256-11e7-8a98-fe39b18766d3.png)
It will stop and says that 

> raises an exception: read access rights conflicts

> fLS::FLAGS_resolution is nullptr
What is wrong here?

**Comment by DarcyWL** [comment]
Also, another mistake happens occasionally...
`Array<T>::toString():
Error:
Index out of bounds: 0 <= index && index < mVolume
Coming from:
- ..\..\src\openpose\core\array.cpp:op::Array<float>::commonAt():429
- ..\..\src\openpose\core\array.cpp:op::Array<float>::commonAt():435`

**Comment by gineshidalgo99** [comment]
About your first image, you should not directly perform cout before the `if (datumsPtr != nullptr && !datumPtr->empty())`. The if statement is checking the datumPtr element is not nullptr, if do you cout before that you might be doing a cout to a nullptr.

In order to cout the keypoints, i've just add an example in:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md#keypoint-format-on-the-opdatum-class
Let me know if that helps you.

And I'll check that `Array::toString():` out of bound. When does it exactly happens?

**Comment by himlen1990** [comment]
same problem happens when I was trying to access keypoints

------------------------------------------here is my code -----------------------------------------------
    void display(const std::shared_ptr<std::vector<op::Datum>>& datumsPtr)
    {
        // User's displaying/saving/other processing here                                                                             
            // datum.cvOutputData: rendered frame with pose or heatmaps                                                               
            // datum.poseKeypoints: Array<float> with the estimated pose                                                              
        if (datumsPtr != nullptr && !datumsPtr->empty())
        {
          int part = 0;
          int person = 0;
          int numberHandParts = 21;
          const auto baseIndex = datumsPtr->at(0).handKeypoints[0].getSize(2)*(person*numberHandParts + part);
          // Left Hand                                                                                                                
          const auto xL = datumsPtr->at(0).handKeypoints[0][baseIndex];
          const auto yL = datumsPtr->at(0).handKeypoints[0][baseIndex + 1];
          const auto scoreL = datumsPtr->at(0).handKeypoints[0][baseIndex + 2];
          // Right Hand                                                                                                               
          const auto xR = datumsPtr->at(0).handKeypoints[1][baseIndex];
          const auto yR = datumsPtr->at(0).handKeypoints[1][baseIndex + 1];
          const auto scoreR = datumsPtr->at(0).handKeypoints[1][baseIndex + 2];

          //std::cout<<xR<<std::endl;                                                                                                 

            cv::imshow("OpenPose ROS", datumsPtr->at(0).cvOutputData);
            cv::waitKey(1); // It displays the image and sleeps at least 1 ms (it usually sleeps ~5-10 msec to display the image)     
        }
        else
            op::log("Nullptr or empty datumsPtr found.", op::Priority::High, __LINE__, __FUNCTION__, __FILE__);
    }
};

---------------------------------------------------log output-----------------------------------------------------------
Error:
Index out of bounds: 0 <= index && index < mVolume

Coming from:
- src/openpose/core/array.cpp:commonAt():430
- src/openpose/core/array.cpp:commonAt():436
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Error:
Index out of bounds: 0 <= index && index < mVolume

Coming from:
- src/openpose/core/array.cpp:commonAt():430
- src/openpose/core/array.cpp:commonAt():436

Aborted (core dumped)

**Comment by gineshidalgo99** [comment]
@himlen1990 You are not check whether there is a person... it might be empty for not finding people
@DarcyWL I still have pending to check toString. I'll keep you posted here.

**Comment by Feifannaner** [comment]
@DarcyWL  I have the  problem just as you want to get the real time data,and NOW I have solved it . You just look at the  src/openpose/gui/guiInfoAdder.cpp 
```
 putTextOnCvMat(cvOutputData, "People: " + std::to_string(poseKeypoints.getSize(0)),
                           {(int)(mOutputSize.x - mBorderMargin), (int)(mOutputSize.y - mBorderMargin)}, white, true);
```
