### ISSUE TITLE
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections

### ISSUE THREAD

**Issue by zhaishengfu** [CMU-Perceptual-Computing-Lab/openpose#13]
thank you for sharing. I compiled successfully but when i run either from video or images, it will stop at such line:
Starting pose estimation demo.
init done 
opengl support available 
Starting thread(s)
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
So, what is the problem?

**Comment by gineshidalgo99** [comment]
Hi, I just though of a possible cause! Could you try this and let us know whether it works?
1. Delete [examples/openpose/rtpose.cpp](../blob/master/examples/openpose/rtpose.cpp).
2. Instead, replace it with this slightly modified version from my Dropbox: [https://www.dropbox.com/s/kgdtw6d0edn7e8v/rtpose.cpp?dl=0](https://www.dropbox.com/s/kgdtw6d0edn7e8v/rtpose.cpp?dl=0).
3. On the main folder: `make clean && make all -j8` (assuming a 8-core machine, no need to do it in 3rdparty/caffe).
4. Try again the same example and command line instruction that you used.

Please, post us whether that solution works and the program output now!

Otherwise, this is the same issue as #4 (even if in your case the warning output is slightly different). You can apply the same solution I posted there. We are trying to find the error meanwhile and your feed-back on the previous possible solution might help us a lot! So please, let us know whether the 1st (and 2nd) solution work!

**Comment by zhaishengfu** [comment]
Thank you. I used your new rtpose.cpp and now I Can use it correctly. more precisely, the following 3 can run well:
1 ./build/examples/openpose/rtpose.bin --video examples/media/video.avi
2 ./build/examples/openpose/rtpose.bin
3.1_extract_from_image
**But when i compile using debug mode, there are still errors with:
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Error:
Cuda check failed (7 vs. 0): too many resources requested for launch

Coming from:
- src/openpose/pose/poseRenderGpu.cu:renderPoseGpu():439
- src/openpose/pose/poseRenderGpu.cu:renderPoseGpu():444
- src/openpose/pose/poseRenderer.cpp:renderPose():285**

So Why This happen? and Why the release can work? Could you tell me what is my problem?? what is the core difference with these 2 files?

**Comment by gineshidalgo99** [comment]
Thank you for your feed-back! I've just added the new rtpose to the repository.

About debug mode, I guess debug mode loads more data to help debug. Could you let me know your hardware characteristics? In particular:
**Operating system** (`lsb_release -a` on Ubuntu):
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
**cuDNN version**:
**GPU model** (`nvidia-smi`):
Compiler (`gcc --version` on Ubuntu):

Thanks!

**Comment by zhaishengfu** [comment]
Ok, My hardare is :
**operating system:** 
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

**CUDA version**
CUDA Version 8.0.27

**cudnn version**
cudnn8.0

**GPU**
GTX-1070

**Comment by gineshidalgo99** [comment]
@zhaishengfu, since your last question is a different topic than the previous one, I am moving it to a new thread so new people can find it easily: #19
Let me know in the new issue thread your cuDNN version (you said cudnn8.0, but the newest version is 6).
Thanks!
