### ISSUE TITLE
Python Standalone detectors (Hands)

### ISSUE THREAD

**Issue by AmitMY** [CMU-Perceptual-Computing-Lab/openpose#1307]
### Type of Issue
- Help wanted
- Question
- Enhancement

### Summary
I have a video I would like to detect the hand keypoints on, but there are just hands, no body (piano playing).
I have trained a custom hands detector, which finds where the hands are, and now I have for every hand a bounding box.

Here is a crop, centering the hand and including some padding.
![image](https://user-images.githubusercontent.com/5757359/61807506-59d95280-ae42-11e9-843f-1c36867c03cc.png)

1. I know there is a C++ standalone hands detector. Is there a Python version as well?
2. For the standalone detector, I couldn't find best practices for image sizes - what crop should be done, I'm assuming centering the hand, but with what padding? what background-color is optimal if we need to add extra pixels? 
3. Just a general question about the data - I currently use an [implementation ](https://github.com/timctho/convolutional-pose-machines-tensorflow) in TensorFlow for the pose estimation, but it is quite bad on my data. Do you know if the data the hands pose model was trained on includes dark images or inconsistent lighting?
![image](https://user-images.githubusercontent.com/5757359/61807892-1206fb00-ae43-11e9-809f-24fcc3578fc0.png)

**Comment by gineshidalgo99** [comment]
1. Everything that works in C++ is analog and works in Python as well.
2. Good question. Let's say about 10-20% margin on the sides of the hand, and squared image. We trained with that configuration. We did not have padding, we simply cropped from the bigger image, so if you can, use the image, otherwise black padding should be fine. I will add this to the doc, thanks!
3. That's not ours. I'd say Openpose should work fine in the kind of images based on what you show above.
