### ISSUE TITLE
complete the miss parts of the pose

### ISSUE THREAD

**Issue by mxmxlwlw** [CMU-Perceptual-Computing-Lab/openpose#131]
Hi,
    Is there any chances to recover the miss parts of the pose key points? Now some of the points will be 0,0,0 first two of which is x and y, last of which is the score of the point. Can I have an estimation of these kinds of data even through it is not as accuracy as the others?

**Comment by gineshidalgo99** [comment]
No there is not for pose, but it is the default behavior for hands and faces.

Technical reason:
With the faces and hands, OpenPose will always return the estimated (x,y,score), even if score is very small, unless no face/hand is found, because we are using single detector there (that is why time is number-of-people dependent).
However, running time of the pose is number-of-people invariant because we do part association. We do not know how many people are in the image, so we need a minimum threshold to consider a body part, so later we can try to infer which body part correspond to each person. So reducing the minimum threshold will simply include lots of non-real-parts to the system and a whole person might most probably be splitted by the algorithm in 2 or 3 people.

Let me know any other question
