### ISSUE TITLE
Configuring incomplete, errors occurred!  

### ISSUE THREAD

**Issue by RatsLoveCats** [CMU-Perceptual-Computing-Lab/openpose#1320]
Cmake's configure and generate are complete, then sudo make -j `nproc` in the build directory will report the following error:（this is the CPU installation, not the GPU）

[ 12%] Performing configure step for 'openpose_lib'
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   regex
--   chrono
--   date_time
--   atomic
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindHDF5.cmake:398 (find_package_handle_standard_args)
  cmake/Dependencies.cmake:47 (find_package)
  CMakeLists.txt:53 (include)

-- Configuring incomplete, errors occurred!
See also "/home/virtual-system/desktop/openpose-master/build/caffe/src/openpose_lib-build/CMakeFiles/CMakeOutput.log".
See also "/home/virtual-system/desktop/openpose-master/build/caffe/src/openpose_lib-build/CMakeFiles/CMakeError.log".
CMakeFiles/openpose_lib.dir/build.make:105: recipe for target 'caffe/src/openpose_lib-stamp/openpose_lib-configure' failed
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/openpose_lib.dir/all' failed
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by HassanAlsamahi** [comment]
I think the problem is that hdf5 is missing, install hdf5 by using
`sudo apt-get install hdf5`

I am assuming that you are using debian based OS

**Comment by gineshidalgo99** [comment]
HassanAlsamahi answer seems right.

**Comment by Edhonack** [comment]
@HassanAlsamahi  Hi! I tried this command. But error appeared
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package hdf5
May I ask how to solve this.
I googled it but the solution doesn't work

**Comment by HassanAlsamahi** [comment]
@Edhonack what distribution are you using?

**Comment by lieyi** [comment]
maybe you can try
sudo apt-get install libhdf5-serial-dev hdf5-tools

**Comment by rajatbindal565** [comment]
> maybe you can try
> sudo apt-get install libhdf5-serial-dev hdf5-tools

maybe you can try
sudo apt-get install libhdf5-serial-dev hdf5-tools

**Comment by Jerry-DanceClout** [comment]
Hey guys, I ran into the same problem, but since I'm installing Openpose into my Macbook, I can't use apt-get. I changed the apt-get to brew install but after:
brew install hdf5
I still get the same result and brew install libhdf5-serial-dev hdf5-tools ends up 👍 Error: No available formula or cask with the name "libhdf5-serial-dev".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps

Can someone help me please? Thanks.

**Comment by bongbonglemon** [comment]
> Hey guys, I ran into the same problem, but since I'm installing Openpose into my Macbook, I can't use apt-get. I changed the apt-get to brew install but after:
> brew install hdf5
> I still get the same result and brew install libhdf5-serial-dev hdf5-tools ends up
> 
> Error: No available formula or cask with the name "libhdf5-serial-dev".
> ==> Searching for a previously deleted formula (in the last month)...
> Error: No previously deleted formula found.
> ==> Searching for similarly named formulae...
> Error: No similarly named formulae found.
> ==> Searching taps...
> ==> Searching taps on GitHub...
> Error: No formulae found in taps
> 
> Can someone help me please? Thanks.

i also have the same issue. any solution? i'm on macos

**Comment by bongbonglemon** [comment]
@Jerry-DanceClout I have found the solution. The issue is with the caffe that came with openpose. It's no good. You should install your own. In fact I found it in the documentation. Here's the [link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#python-api) and here it is for quick reference:

Also as a side note, if the default installation fails (i.e., the one explained above), install Caffe separately and set BUILD_CAFFE to false in the CMake config. Steps:

Re-create the build folder: `rm -rf build; mkdir build; cd build`.
`brew uninstall caffe` to remove the version of Caffe previously installed via cmake.
`brew install caffe` to install Caffe separately.
Run cmake-gui and make the following adjustments to the cmake config:
BUILD_CAFFE set to false.
Caffe_INCLUDE_DIRS set to /usr/local/include/caffe.
Caffe_LIBS set to /usr/local/lib/libcaffe.dylib.
Run Configure and Generate from CMake GUI.
