### ISSUE TITLE
Skeleton thickness don't stay homogeneous at all resolutions.

### ISSUE THREAD

**Issue by AndroXD** [CMU-Perceptual-Computing-Lab/openpose#1341]
This affects every OpenPose version regardless of the OS, machine or configuration.

If I output a skeleton from a 1920 x 1080 photo ( https://i.imgur.com/2Zylqdh.png ) and resize it to 1280 x 720, then output a skeleton from the same exact photo resized at 1280 x 720 ( https://i.imgur.com/vfM3oH0.png ), the resulting bone thickness between the two skeletons will appear very different when compared together ( https://i.imgur.com/Oe2ZkT2.png ), this happens especially on distant people ( if you want to reproduce this issue: picture at 1920 x 1080 https://i.imgur.com/68ejKo6.jpg same picture at 1280 x 720 https://i.imgur.com/3miLmad.jpg ), how can I make sure the bone thickness always stay consistently the same when using the same footage but at different resolutions?

I believe data consistency is very important for any scientific scenario, in fact this can be a pure nightmare for deep learning, imagine having several low resolution pictures which you cannot detect the skeleton from, but the high resolution ones will, however, since the model has been trained on the low resolution pictures, the resized pictures will output an erroneous result due to the data inconsistency, I've seen stuff like this happen for not noticing a 1px border completely invisible to the naked eye, imagine how many things could go wrong when the thickness difference is so noticeable.

I'd really appreciate any ideas or solutions to solve this, thanks!

**Comment by gineshidalgo99** [comment]
The skeleton is meant only for visualization purposes, it does not affect the results at all (e.g., the JSON files provide fixed results, which is the only thing that matters from a scientific point of view). Visualization is not important.

I'd say what you want are the heatmaps, which are resized to `--net_resolution`, so as long as you maintain a fixed net resolution between different videos (which is the default behaviour), the results should be consistent.

Still, if you are using the visual output for anything else, I'd recommend you to create a visual output consistent to whatever application you are trying to do, because visual results are meant to be just for visual purposes.

You could also try something more similar to our CPU visualization (compatible with GPU computing), which provides a line rather than an ellipse. That would make more sense if you are using it as input of something else. (But again, I'd not recommend using the visual output for anything else).

**Comment by coreygmorris** [comment]
Could you please elaborate on how would you use the CPU visualization with the GPU computing to get the line rather than the ellipse?

**Comment by AndroXD** [comment]
I guess by CPU visualization you mean the flag "**-render_pose 1**", I can see the advantage in using lines instead of ellipses for my case scenario, but unfortunately it's still inconsistent as you can see here: https://i.imgur.com/CAcqfkC.png
On my 1280x720 picture the joints appear as squares instead of spheres and on the 2560 x 1440 picture the bones appear thinner than the rest, as you can see the bigger pictures will often detect features better than the low resolution ones (ie. the eyebrows and eyes), which is why I'm trying to do this.
I agree that the JSON output is definitely the best option for consistency, but how would I use that to generate a picture of a custom skeleton that line up perfectly with a photo? Some documentation (HOW TO) on how to implement that (or a tool) would be very helpful, I'm not the first one who requested such a feature (ie. issue [#568](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/568)), customizing skeletons (ie. to change colors) is definitely something many have wanted at some point to fit their specific case scenarios.

**Comment by gineshidalgo99** [comment]
Again, it is only meant for quick visualization. For a more complex representation, feel free to implement one for your own purposes.
Unfortunately, it is not easy to customize because CUDA (GPU version) requires to hard-code the values, so they can be added as a variable easily. Again, this is a very quick visualization, only intended for demo purposes.
