### ISSUE TITLE
Jetson TX 1 demo, Error: Videocapture (webcam) could not be opened

### ISSUE THREAD

**Issue by shaktidhar** [CMU-Perceptual-Computing-Lab/openpose#135]
Platform: Jetson TX1 
OS : Ubuntu 16.04 
OpenCV : 2.4.13
Camera : CSI 
CUDA 8.0 

I have gone with default installation. There were minor issues in lhdf5 which were resolved. 
After completing the setup, all models were downloaded as well. 

But when I run the demo, I get an error. I have tried with options, --camera 0  to --camera 9. 

I realize Jetson TX1 is not officially supported yet. If someone has inputs on how to get openpose to detect camera, that will be great. 

[Update]
It appears the problem may have something to do with OpenCV.

**Comment by callemein** [comment]
Have you tried opening the webcam with a simple OpenCv program? Sometimes it's just a permission problem.

**Comment by gineshidalgo99** [comment]
Is it working with `image_dir`? and `video`? See the FAQ in the doc/installation.md to see some tips about it.

**Comment by raghavg96** [comment]
Can you share the error log?

**Comment by shaktidhar** [comment]
@gineshidalgo99  Yes, it works with images and video. I will check the FAQ. 
@callemein  and @raghavg96  I am travelling, allow me a day, will check and post more details.

**Comment by metropt** [comment]
BTW which FPS do you get with video?

**Comment by shaktidhar** [comment]
The simple OpenCV program using Video=0 didn't work. 
I guess the issue has been with OpenCV and some further settings are needed. 

I am erasing everything to start afresh. This time, I will use a separate USB camera instead of the CSI onboard camera.

**Comment by shaktidhar** [comment]
@metropt  Not sure what you mean by 'which FPS' ...

**Comment by metropt** [comment]
@shaktidhar I want to know how it run on the jetson

**Comment by shaktidhar** [comment]
When using video, I was getting ~10 FPS.

**Comment by metropt** [comment]
what net-resolution did you select?

**Comment by shaktidhar** [comment]
I went with the default. Didn't change those.

**Comment by gineshidalgo99** [comment]
Thanks @liutao2017 for the info. I guess that was the problem so I am closing this.

**Comment by Sindreedelange** [comment]
@liutao2017, I was wondering if you could be a little more specific about the fix for opening the on board camera? It is my understanding that OpenPose uses opencv to use the web camera, but in order to open the on board web camera on the Jetson tx2, one needs the code line:
`cap = cv2.VideoCapture("nvcamerasrc ! video/x-raw(memory:NVMM), width=(int)1280, height=(int)720,format=(string)I420, framerate=(fraction)30/1 ! nvvidconv flip-method=0 ! video/x-raw, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink")`
Maybe @gineshidalgo99 can advice on which file to edit, in order to add this code snippet?

**Comment by gineshidalgo99** [comment]
@Sindreedelange Use the examples/tutorial_api_* examples, in particular the one in which you control the input. And then implement your own input (with this snippet) on it.

**Comment by Sindreedelange** [comment]
@gineshidalgo99 I am sorryy, but I'm not following. So in examples/tutorial_api_*, let's say examples/tutorial_api_python, then there should be a .py script in that folder, in which I can control the input. Would this be in 04_keypoints_from_images.py here:
![image](https://user-images.githubusercontent.com/9415625/56791311-0cc7ef00-6807-11e9-8bc1-9c4d395c0389.png)
?

Maybe if I tell you my use case, it would be easier. I want to run an OpenPose demo on the Jetson TX2 web cam, where the output should be the web cam feed with keypoints overlaied, using the COCO model (18 keypoints). Basically the 'standard' OpenPose demo, but where I can define the web camera input, because apparently it's not so easy for the program to find.

**Comment by gineshidalgo99** [comment]
Yes, take any of those examples, and add your custom input (i.e., your particular webcam in your case)
