### ISSUE TITLE
Quick Start example error

### ISSUE THREAD

**Issue by devropes** [CMU-Perceptual-Computing-Lab/openpose#1355]
I downloaded "openpose-1.5.1-binaries-win64-only_cpu-unity.zip" from https://github.com/CMU-Perceptual-Computing-Lab/openpose/releases. Then I followed the "Instructions.txt". After that, I finally ran the command "bin\OpenPoseDemo.exe --video examples\media\video.avi" from https://github.com/CMU-Perceptual-Computing-Lab/openpose#quick-start. However I ended up getting the below error. How can I fix this?

`The procedure entry point ?GetDefaultDevice@Caffe@caffe@@SAPEAVdevice@2@XZ could not be located in the dynamic link library C:\Users\Alex\Desktop\openpose\bin\openpose.dll.`

I use CPU on Windows 10

**Comment by gineshidalgo99** [comment]
Does it happen with 1.5.0? Can you add your hw config as the github issue template indicated?

**Comment by AndroXD** [comment]
In my experience, the file "**openpose-1.5.1-binaries-win64-gpu-python-flir-3d_unity.zip**" from Release version 1.5.1 would display that error, but file "**openpose-1.5.1-binaries-win64-gpu-python-flir-3d_recommended.zip**" works fine out of the box.
Hope this helps to narrow the problem, if there are any.

**Comment by Lininggggggg** [comment]
> I downloaded "openpose-1.5.1-binaries-win64-only_cpu-unity.zip" from https://github.com/CMU-Perceptual-Computing-Lab/openpose/releases. Then I followed the "Instructions.txt". After that, I finally ran the command "bin\OpenPoseDemo.exe --video examples\media\video.avi" from https://github.com/CMU-Perceptual-Computing-Lab/openpose#quick-start. However I ended up getting the below error. How can I fix this?
> 
> `The procedure entry point ?GetDefaultDevice@Caffe@caffe@@SAPEAVdevice@2@XZ could not be located in the dynamic link library C:\Users\Alex\Desktop\openpose\bin\openpose.dll.`
> 
> I use CPU on Windows 10

hello, maybe you can ran the command "build\x64\Release\OpenPoseDemo.exe --video examples\media\video.avi", just change the path of OpenPoseDemo.exe

**Comment by devropes** [comment]
@AndroXD I noticed that too. @gineshidalgo99 I also tried 1.5.0, and the error was gone.
However, I noticed the examples just freeze on the 1st frame. Aren't the examples supposed to support CPU? How can I fix this?

**Comment by gineshidalgo99** [comment]
@AndroXD So how are you testing the unity version? It is supposed to be used only within Unity.
@devropes It does not freezes. CPU simply takes a few seconds per image

**Comment by AndroXD** [comment]
>So how are you testing the unity version? It is supposed to be used only within Unity.

I thought they worked both ways, within or outside of Unity, because when I tried the Unity plugin [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose_unity_plugin), I could run this command and it would work just fine:
`bin\OpenPoseDemo.exe --video examples\media\video.avi --face --hand --disable_blending --number_people_max 1`
As long as the models (face, hand, pose) were inside their respective folders, it doesn't show that error above.

**Comment by gineshidalgo99** [comment]
You should not use the Unity version outside Unity. Because it'll work as long as it works, but when an error is thrown, the OP Unity version will crash because it'll try to send the error to Unity.

Conclusion: Both should work, but the OP Unity version will crash if if faces an error outside Unity.
