### ISSUE TITLE
Different versions of ffmpeg and nvidia driver make the result different?

### ISSUE THREAD

**Issue by ro6842** [CMU-Perceptual-Computing-Lab/openpose#1365]
I try to run the Demo(./build/examples/openpose/openpose.bin --video examples/media/video.avi)
on my Ubuntu system(  nvidia driver version: 367.48  and ffmpeg version: 2.8.15  ). It can show me nice result.

But when I change to another Ubuntu system(  nvidia driver version: 381.22  and ffmpeg version: 3.3.8  ), and run the same Demo video. I got the different result.

Can anyone tell me whether differnt version of installment make the result different?

**Comment by gineshidalgo99** [comment]
FFMPEG could definitely make a difference. Try converting the video to images. And then copy those same images into the 2 Ubuntu systems and check the results then. If they do not change (my guess), then it is FFMpeg.

Otherwise, Nvidia (thus also CUDA) could definitely make a difference.

Other than that, OpenPose should be fully deterministic assuming you are using the exact same OpenPose version (we also keep iteratively improving across newer versions).

(Feel free to answer even after it is closed, e.g., if those 2 are not the issue)

**Comment by ro6842** [comment]
Sorry, bothering again.

In order to test whether FFMPEG influences results. I try converting the video to images. And then copy those same images into the 2 Ubuntu systems and check the results. But I also got the different result. So I think it's not the problem of FFMPEG.

I check the two Ubuntu system again. I found the size of "openpose.bin" is different. The one is 146kb(nice results), but the other is 131kb(bad results).
So I want to ask whether different Makefile.config setup makes the result different?
If it's right, I just need to use the same Makefile.config and make again?

I am afraid I do the wrong steps resulting in the Openpose can't run. So make sure again.
Thank you!!
