### ISSUE TITLE
How to generate hand/face heatmap together with pose heatmap with op?

### ISSUE THREAD

**Issue by menjarleev** [CMU-Perceptual-Computing-Lab/openpose#1381]
Hi there, I can only manage to generate the 25 coordinate heatmap of the pose. But I want to get the heatmap of hand&face as well and to concatenate them to the pose heatmap. Is there any way I can do it?

**Comment by gineshidalgo99** [comment]
Heatmap is obtained for the whole image (body run at the whole image). Face and hands are manually cropped and fed individually. So the concept would be different and the size variable, that's why there is no easy way to do that. However, the same flags for body can be used to generate each face/hand heatmap and you can manually concatenate it.
