### ISSUE TITLE
cuda render error

### ISSUE THREAD

**Issue by zhaishengfu** [CMU-Perceptual-Computing-Lab/openpose#14]
I run your program 1_extract_from_image.cpp and it says:
**
Error:
Cuda check failed (7 vs. 0): too many resources requested for launch

Coming from:
- src/openpose/pose/poseRenderGpu.cu:renderPoseGpu():439
- src/openpose/pose/poseRenderGpu.cu:renderPoseGpu():444
**
what is the problem??
Ｉfind it the error lies in line 238 of poseRender.cpp:
renderPoseGpu(*spGpuMemoryPtr, mPoseModel, numberPeople, mOutputSize, pGpuPose, mShowGooglyEyes, mBlendOriginalFrame, mAlphaPose);
Please help me.

**Comment by gineshidalgo99** [comment]
Hi, I never saw this error before with this program. Could you try the following?
1. Does the same error occurs when executing the demo with the default parameters? I.e. `./build/examples/openpose/rtpose.bin --video examples/media/video.avi`.
2. Which command are you using?

In addition, which hardware are you using?
**Operating system** (`lsb_release -a` on Ubuntu)
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases)
**cuDNN version**
**GPU model** (`nvidia-smi`)

Thanks!

**Comment by zhaishengfu** [comment]
Ok, My hardare is :
operating system:
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

CUDA version
CUDA Version 8.0.27

cudnn version
cudnn8.0

GPU
GTX-1070

and my cpu is 4 core

**Comment by vwrs** [comment]
I got the same error on Jetson TX1, so I changed `--net_resolution`, it works.

**Comment by gineshidalgo99** [comment]
OK, then the problem is the huge shared GPU memory required.

Instead of reducing the --net_resolution (it will drop accuracy), I think you can alternatively reduce the maximum amount of people detected (right now 96, but will you really have up to 96 people on the image?).

It is called POSE_MAX_PEOPLE, and it is located on [https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/include/openpose/pose/poseParameters.hpp](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/include/openpose/pose/poseParameters.hpp).

I guess a value of 20 or 30 might work. Please, perform `make clean && make all -j8` after you change it.

And let me know whether it works. Thanks!

**Comment by vwrs** [comment]
I set `POSE_MAX_PEOPLE` to 2, but still got the same error.
At this time, the only solution is to reduce `--net_resolution` and/or `--resolution`, but it still keeps enough accuracy.

**Comment by gineshidalgo99** [comment]
OK thank you for the feedback. In 1-2 weeks, we are planning to release a ~30% faster version, which will require less GPU memory (approx same accuracy). It might then work in your case. Please check OpenPose for near future releases. We will change 1.0.0rc2 to 1.0.0rc3 or 1.0.0 when we release it so you can easily check it.
