### ISSUE TITLE
Guide to run as Restful API.

### ISSUE THREAD

**Issue by ran2207** [CMU-Perceptual-Computing-Lab/openpose#1452]
I am having difficulty in running this package as a Webservice. Would appreciate if we could provide any kind of documentation on implementing an API to get the keypoints from an image. Our aim is to able to deploy this API as an Azure Function and also know if it is feasible.

**Comment by gineshidalgo99** [comment]
For such documentation, check the examples:
For C++: https://github.com/CMU-Perceptual-Computing-Lab/openpose/tree/master/examples/tutorial_api_cpp
Or for Python: https://github.com/CMU-Perceptual-Computing-Lab/openpose/tree/master/examples/tutorial_api_python

And the doc itself:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/tree/master/doc
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/demo_overview.md
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md

For the rest, please, provide your full hardware configuration as the GitHub issue template showed. We haven't tried Azure, so you need to fill this info for us to be able to help with the problems you are facing with those.

**Comment by suprnrdy** [comment]
@ran2207 to get something up and running quickly in python, you could set something up using flask (https://towardsdatascience.com/simple-way-to-deploy-machine-learning-models-to-cloud-fd58b771fdcf) and instead of loading the model, you would start the OpenPose framework and  then inside a 'get_prediction' function you would put some code like: 

`# Process Image
    datum = op.Datum()
    imageToProcess = cv2.imread(args[0].image_path)
    datum.cvInputData = imageToProcess
    opWrapper.emplaceAndPop([datum])`

and your api could respond with the keypoints:

`datum.poseKeypoints`

Hope this helps.

**Comment by rafinskipg** [comment]
Hey people, coming from other programming languages I find this documentation really counter-intuitive. Is there any full example of an API working with openpose and python?
