### ISSUE TITLE
Increase performance by reducing detection area

### ISSUE THREAD

**Issue by AndroYD84** [CMU-Perceptual-Computing-Lab/openpose#1486]
### Type of Issue
- Enhancement / offering possible extensions / pull request / etc

Usually bigger pictures takes longer to process as OpenPose tries to detect people on the entire picture, but sometimes it's known that a target person will always stay in a specific small area (ie. a person poledancing) and never move out from there for the entire clip (ie. imagine a 256x512 area out of a 1920x1080 picture), so it would be faster to crop that area in 256x512 pictures and run OpenPose on them, but then the JSON aligments won't match with the original 1920x1080 pictures anymore, making them unusable, would you consider adding a feature that allows to focus only on a smaller area to speed up detection considerably? It's SO much faster when I crop the pictures first, but I also need the JSON data to align with the originals afterwards. I think that would be a really useful feature, especially on landscape shots where the person is usually at the center and their left and right have nothing important to detect.

**Comment by gineshidalgo99** [comment]
The speed would be the same, OpenPose resizes the image to a smaller resolution before running. If you see a FPS drop is because you are using really big images, maybe, so resizing the image down is slow.

Accuracy-wise, if you know where the person is, then yes, it should improve the accuracy. But using multi-resolution setup also gives you similar (or even better) accuracy, without needing to feed OpenPose with the person location.

This is not a utility we are considering to add, given the very low benefits (speed in very rare cases), but PRs are welcome!

**Comment by kartikJ-9** [comment]
When i am cropping the area, the JSON obtained is having absurd 0 values. Any fix for that?
