### ISSUE TITLE
did anybody know why crop affect PAF so much?

### ISSUE THREAD

**Issue by chenmingjian** [CMU-Perceptual-Computing-Lab/openpose#1615]
### Issue Summary
as title. we can see in the first picture paf_y is very strong, but in crop picture is bad then full one.

![test1](https://user-images.githubusercontent.com/21312069/84774549-912f8f80-b010-11ea-857a-9e753634d545.jpg)
![test2](https://user-images.githubusercontent.com/21312069/84774561-955bad00-b010-11ea-8297-7c31fb976dc6.jpg)

It's confuse me. Thank you in advance.

### Type of Issue
- Question

**Comment by gineshidalgo99** [comment]
You should leave some padding around the person (eg 1/10th of the person bounding box side). If the keypoint (in this case the elbow) is in an image edge, it is harder for the algorithm to detect it (given how CCNs work), that's why the weird artifact. It should match and work better with that padding.

**Comment by chenmingjian** [comment]
@gineshidalgo99 thx for reply.
