### ISSUE TITLE
How to Perform Hand detection

### ISSUE THREAD

**Issue by alecda573** [CMU-Perceptual-Computing-Lab/openpose#1710]
I am wondering if their is a flag I can use so I also detect hand keypoints while detecting body keypoints at the same time. Currently, I am getting the body keypoints by using:

cmdline = [os.path.join('bin', 'OpenPoseDemo.exe'), '--video', video_path, '--write_json', output_path,'--net_resolution',net_resolution]

**Comment by gineshidalgo99** [comment]
--hand

**Comment by alecda573** [comment]
@gineshidalgo99 thats what I would have assumed to but this just gets me an error:

subprocess.CalledProcessError: Command '['bin\\OpenPoseDemo.exe', '--video', 'D:\\SmithfieldVideos\\M2U00002.MPG', '--write_json', 'C:\\Users\\alecd\\Downloads\\output\\M2U00002.MPG', '--net_resolution', '336x336', '--hand']' returned non-zero exit status 3221226505.

**Comment by gineshidalgo99** [comment]
That looks like an out of memory? How many GBs of memory does your GPU have?

To test whether that's the issue, try `--net_resolution 128x128 --hand_net_resolution 128x128` and see if that way it works (the quality will be terrible, this is just to test whether it's the memory)

**Comment by alecda573** [comment]
@gineshidalgo99 Ah that did it! Thanks very much this machine only has 6gb on it. Should moved over to the titan 👍

**Comment by alecda573** [comment]
@gineshidalgo99 just as one last question -- does it fail at detecting hands only?

**Comment by gineshidalgo99** [comment]
Yes, body is required in order to detects the hands bounding box location where to perform hand keypoint detection.

If you have standalone hand bounding boxes (or you have some kind of hand bounding box detector), then you can check the C++ examples for those cases:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/standalone_face_or_hand_keypoint_detector.md
