### ISSUE TITLE
Ubuntu:acceleration of single person

### ISSUE THREAD

**Issue by peixinx** [CMU-Perceptual-Computing-Lab/openpose#173]
### Issue summary
I had successfully run on my ubuntu. I'd rather detect only single person with a higher speed. How can i speed it up by adjusting the structure?

**Comment by gineshidalgo99** [comment]
The whole algorithm is meant for multi-person, using it for single-person is not possible. You can decrease the `net_resolution` to only get the biggest people in the scene and the other speed up options from the FAQ section in the doc/installation file.

**Comment by Feifannaner** [comment]
@gineshidalgo99  how about the render one biggest  person in video? Refereed at #180   I think it will speed up the algorithm if  detect only one person in image. 
 However , I think the method in the #180 not be available in the new version,because I failed in the camera detecting process. but I found the  line68 in render.hu will work, and it will display only one person. but the function
```
for (auto person = getBiggestPerson(keypoints, threshold); person < keypoints.getSize(0) ; person++)
``` cannot work ,so we will not sure who is the biggest person.
i do not know .hu file;s function in the openpose project. Can you help me?Thank you!

**Comment by gineshidalgo99** [comment]
I never tried that function, I have no idea what it'd do.

But render time is <1% of the total time, the speed up would be basically none. Detection of all people is most of the processing time, so only rendering 1 person does barely help at all for speed, that is why there is no easy option to keep only 1 person, I am sorry.
