### ISSUE TITLE
How to feed Python array directly to OpenPose without saving to image file

### ISSUE THREAD

**Issue by PetteriLaitinen** [CMU-Perceptual-Computing-Lab/openpose#1745]
Hi!
Thanks for the great work with OpenPose!
This is a Python API related question/issue/suggestion.

I am working with artistic gymnastics videos. Because of the nature of the videos, I am trying to crop and rotate the pictures before feeding them to OpenPose to increase the quality of predictions. 

Today, I can do this by cropping, rotating and saving the image as file. Then I read the image from file into OpenPose.
However, this seems unnecessary, but I have not figured out a way how to read a numpy array or similar directly to the OpenPose.
Do you have an easy example of this? Could such an example be added to the tutorial_api_python folder?

My system: Win10, Python3.7

Hope the question makes sense and this is the right place to ask. Thanks!
Br., Petteri

**Comment by frankier** [comment]
Terve!

This is already possible. However in many cases it is more efficient to do preprocessing first and let OpenPose do the ingestion. The reason is that if you feed in things through the Python API you essentially make the Python code and OpenPose go in serial one and then another every frame -- they do not run in parallel unless OpenPose does its own ingestion.

This is the line that assigns the numpy image array: https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_python/04_keypoints_from_images.py#L69

Note that it is in OpenCV format so it goes BGR rather than RGB. You can use `cv2.cvtColor(frame, cv2.COLOR_RGB2BGR, frame)` if you have RGB.

**Comment by PetteriLaitinen** [comment]
Thanks! That had passed my eyes. And extra 🙏 for the rgb vs bgr tip!!
