### ISSUE TITLE
About run on RTX 3070

### ISSUE THREAD

**Issue by luojc123** [CMU-Perceptual-Computing-Lab/openpose#1750]
I build it with GTX 1080 but it can't run on the computer with RTX 3070 and no error message.
Is cuda version incompatibility?

**Comment by richardun** [comment]
Hi, luojc123.  I have a similar issue.  I have an RTX 3080 and learned about the CUDA support for various architectures.  This page might help you:  https://en.wikipedia.org/wiki/CUDA  You need CUDA 11.1 like me... because that's the one that supports the compute capability (8.6).  So, you must install CUDA 11.1 to get use out of your card.  Good luck.

**Comment by gineshidalgo99** [comment]
Hi @luojc123 @richardun @diepgfai @templarares ,

I have pushed to GitHub the latest OpenPose working (hopefully!) with CUDA 11 and cuDNN 8 in both Windows and Ubuntu.

Note: OpenPose v1.6.0 binaries will never work with CUDA 11 / RTX 30XX cards, I am talking about the source code itself.

In a few days I will push OpenPose v1.7.0 (and its Windows pre-compiled binaries), so people won't need to compile OpenPose. However, before doing that, I'd like to ask you all to confirm whether the latest OpenPose is working with the RTX 30XX. Please, post here whether it works or not (and your OS: Windows or Ubuntu), or the new bugs if not!

Thanks

**Comment by gineshidalgo99** [comment]
See #1747 and post in there, please do not post in here. I won't reply in this thread anymore. Thanks!

**Comment by richardun** [comment]
Hi Ginés,

Thank you for working on this today!  I'll try to build this tomorrow
morning and let you know.

Cheers,
R

**Comment by gineshidalgo99** [comment]
Thanks @richardun ! Waiting for your answer
