### ISSUE TITLE
this message pops up “Check failed: error == cudaSuccess (2 vs 0) out of memory”

### ISSUE THREAD

**Issue by justinjohn0306** [CMU-Perceptual-Computing-Lab/openpose#1772]
This message pops up “Check failed: error == cudaSuccess (2 vs 0) out of memory” when I try to run this command "bin\OpenPoseDemo.exe --video output\CaptureTest.mp4 --write_json output --face --write_video output\CaptureTest.avi"

although it works fine with V1.5.1 "openpose-1.5.1-binaries-win64-gpu-flir-3d_recommended.zip"

Think this is a bug with the latest build.

**Comment by Malu202** [comment]
I think this has something to do with the video orientation. For me (1.7.0 GPU demo) this happens only with landscape videos, portrait videos works fine. If you use --frame_rotate 90 (or 270) on landscape videos the computation starts. But if the persons are not upright then it yields not very good results obviously.

Can confirm this was working in the 1.6.0 release, although there it was not possible to use --frame_rotate.

**Comment by gineshidalgo99** [comment]
Newer CUDA versions use more and more GPU memory, so that's why newer OpenPoses use more memory (as they use newer CUDAs).

What is your video resolution? @Malu202 You can also see #1811 (and post in there if questions arise), pretty much change `net_resolution` to `net_resolution 656x368` to avoid issues with non-horizontal videos
