### ISSUE TITLE
Makeathon University of Michigan - What webcam should we buy?

### ISSUE THREAD

**Issue by EdgarBolivar** [CMU-Perceptual-Computing-Lab/openpose#1827]
Dear OpenPosers,

First, let me congratulate you on this great open-source initiative. It opens the possibilities to many projects within the biomechanics field.

Here at the University of Michigan, we are designing a Makeathon for interested graduate-undergraduate students. One of the projects involves your tool (details are below). Our questions are, Do you have recommendations about the quality of the video/lighting/environment in order to estimate joint angles? Do you have a specific camera that you recommend (preferably a WebCam or that can transmit video through USB)? Our idea is to provide each team with a WebCam and we wanted to know your opinion before we start purchasing.

Any information is appreciated. Thank you for this initiative!

Edgar

# Measuring Rehabilitation Outcomes with OpenPose
For Prosthetists and Orthotists, it is important to measure objective rehabilitation outcomes to asses patient progress. These rehabilitation outcomes typically include specific metrics of the human lower-limb kinematics, such as step length, cadence, and Range of Motion (RoM) of the joints. These metrics are available using motion capture systems, e.g., using [Vicon](https://www.vicon.com/) or [XSens](https://www.xsens.com/). However, the cost of these systems makes these kind of analyses prohibitive for most clinicians. **The objective of this project is to create an open-source tool to analyse human lower-limb kinematics from video recordings taken from a smartphone or webcam.** Fortunately, we can leverage the results from the [OpenPose](https://github.com/CMU-Perceptual-Computing-Lab/openpose) project to materialize this objective!
# The challenge
## Easy
* Estimate ROM of the knee and ankle joints from a video recording. Offline or real-time estimation is valid.
* Auto-generate a pdf file that reports the mean, median, maximum, and minimum ROM for each joint for the complete length of the video.
## Medium (includes objectives at easy level)
* Calculate the step length and cadence.
* Include the mean, median, maximum, and minimum step lengths and cadences in the pdf report.
* Include a plot of the joint angle vs. time for the knee and ankle joints. Select a time window that is easy for visualization and is representative of the data.
## Spicy (includes objectives at medium level)
* Fragment the joint angles of the knee and ankles in multiple time windows. Each time window should include exactly one gait cycle.
* Include a violin plot to report the statistics of the ROM, step length, and cadence.
* Create a real-time video that shows in parallel the motion of the patient with the skeleton from OpenPose, the joint angle vs. time for the knee and ankle, and the statistical information from the the data currently in display.

# Resources
1. [OpenPose](https://github.com/CMU-Perceptual-Computing-Lab/openpose)
1. Webcam 1080P HD.

# Constraints
1. Develop the tool for Windows 10/8. Our alpha test will be to deploy our tool at the UM-Orthotics and Prosthetic Center ([UMOPC](https://www.uofmhealth.org/our-locations/south-industrial-op)).  The UMOPC will have access only to Windows machines.

**Comment by gineshidalgo99** [comment]
Hi @EdgarBolivar ,

**Camera:**
Estimating joint angles would be way easier with 3D cameras (either multicamera or cameras with depth information like Kinect or I think RealSense also has depth?). That would be my choice for "simple" joint angle detection.

If you really want to use a webcam (because you eventually wanna run on eg a phone), I personally really like the quality of the Logitech 920 and 930 cameras
https://www.amazon.com/Logitech-C930e-960-000972-USB-Webcam/dp/B00CES5A60/ref=sr_1_3?crid=1R49V2FK4V4IO&dchild=1&keywords=logitech+webcam+930e&qid=1610318555&sprefix=logitech+webcam+930%2Caps%2C-1&sr=8-3
https://www.amazon.com/Logitech-C920x-Pro-HD-Webcam/dp/B085TFF7M1/ref=sr_1_6?dchild=1&keywords=logitech+webcam+920&qid=1610318566&sr=8-6

But it is based on my personal experience! I am not saying the are the absolute best, but I do like them a lot. And again, joint angles from 2D will not achieve the same quality than with 3D data (eg running OpenPose on a Kinnect and with the depth channel getting the Z coordinate).

**video/lighting/environment**
OpenPose (and most COCO-based detectors) is usually robust to these 3, I would not worry much about those conditions other than the following:
- I'd try to use videos of people with no occluded limbs, or it would complicate a lot the post-processing that the students would have to do and the quality of the OpenPose results (thus the quality of their results).
- Also, videos with people looking forward will also be easier for OpenPose than profile views where the limbs will overlap.
- And finally, overlapping people would also complicate things.

(Closing this to minimize open GitHUb issues, but i'll keep replying following questions!)

**Comment by EdgarBolivar** [comment]
Thank you, @gineshidalgo99 !

You gave us some great options. Based on your input, we will switch to cameras with depth information like the [real sense with lidar](https://www.intelrealsense.com/lidar-camera-l515/) or the latest [kinect](https://www.microsoft.com/en-us/p/azure-kinect-dk/8pp5vxmd9nhq?activetab=pivot:overviewtab).

We will start with a single camera and build from there. Unfortunately, we are mostly interested in the motion in the sagittal plane. We expect limbs overlapping and will take your recommendations into account.

Thank you again and we will keep you posted if we get interesting results.

**Comment by gineshidalgo99** [comment]
No problems, happy to help. Good luck with the course!

**Comment by EdgarBolivar** [comment]
All right, we went for the Azure Kinect DK. 

Most of our students do not have access to a dedicated GPU, do you have some tips for running OpenPose with a CPU only? We are ok with offline processing, but real-time would not hurt at all.

Thank you for all the support!

**Comment by gineshidalgo99** [comment]
Well, that's the problem of deep learning, you need a buffy machine. CPU is just too slow in comparison.

I know some people have used Docker / Google Colab, and there are some instructions that the community added in the past:
https://cmu-perceptual-computing-lab.github.io/openpose/web/html/doc/md_doc_installation_0_index.html

But I can't say I have used them or that we really support them yet sadly :( But always happy to accept pull requests about improvements in those topics!

**Comment by EdgarBolivar** [comment]
Thanks a lot! We will have access to the kinect soon and will try performance with the CPU only for offline processing. We will keep you posted on our progres.  :)

**Comment by fweidner** [comment]
I second the recommendation of the c920 - we got pretty good results with it.
