### ISSUE TITLE
Compilation/installation error: Wrong OpenCV path

### ISSUE THREAD

**Issue by AntoinePiro** [CMU-Perceptual-Computing-Lab/openpose#1846]
I am trying to run the example from the QuickStart section after compiling from source on Ubuntu 16.04.

Running 
```./build/examples/openpose/openpose.bin --video examples/media/video.avi --face --hand --write_json output_json_folder/```

I get:
```
Error:
OpenCV(4.0.0-pre) /home/antoine/Documents/opencv/modules/highgui/src/window.cpp:615: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvNamedWindow'
```

While i set up ```OpenCV_Dir``` to be ```/usr/local/lib/cmake/opencv4``` with ```cmake-gui```.

Why does my code tries to access this location for opencv ?
And how can I fix it ?

Any help is welcome :)

Thank you

**Comment by gineshidalgo99** [comment]
This is a 3rd party issue, so we technically do not support it.

Still, if you are in Ubuntu, the OpenCV given with apt-get install does not fail, so you could try that one. Otherwise, if you really have to compile it yourself for some additional reason, try exploring the error on OpenCV forums to know which libraries you need to enable, although I think the message is telling you already what you need? (ie adding GTK on OpenCV Cmake?)
