### ISSUE TITLE
getBaseModels.bat error

### ISSUE THREAD

**Issue by EdgarBolivar** [CMU-Perceptual-Computing-Lab/openpose#1934]
Hi,
I am installing OpenPose with the Windows Portable Demo. 

As soon as I execute `getBaseModels.bat` I get the following error:

`--2021-05-01 13:02:18--  (try: 2)  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/body_25/pose_iter_584000.caffemodel
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... failed: Unknown error.
Retrying.`

How can we get by this issue? Thank you!

**Comment by ravijo** [comment]
@EdgarBolivar 

The error description you provided is insufficient to debug the issue.

I suggest you execute it again. OR download the file manually using your internet browser by opening http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/body_25/pose_iter_584000.caffemodel

I assume you are behind a proxy server or your internet network has some restrictions. Sometimes because of the network restrictions, it is difficult to reach the target server.

**Comment by EdgarBolivar** [comment]
Thank you @ravijo ! I just downloaded the file manually.

**Comment by ravijo** [comment]
@EdgarBolivar, I am glad to hear. Additionally, please close the issue if you feel that it is solved.

Cheers!
