### ISSUE TITLE
failed to download models

### ISSUE THREAD

**Issue by bobluoluo** [CMU-Perceptual-Computing-Lab/openpose#1943]
Model download links seems to broken. ( Weird, I downloaded the models a few weeks ago. there was no issue.)
duplicate: ./getModels.sh

![image](https://user-images.githubusercontent.com/56043227/118373934-53701980-b587-11eb-97ba-dd5871654ea4.png)

**Comment by ifselimh** [comment]
Seems like http://posefs1.perception.cs.cmu.edu/ doens't work at all. I can't download models too.

**Comment by GunLengend** [comment]
I have similar issues, the link somehow doesn't work at all.

**Comment by happypanda5** [comment]
Same issue here. I really hope the download links are fixed 

@gineshidalgo99 would appreciate if you can look into this.

**Comment by IBNU1** [comment]
I've had a similar issue.

**Comment by IBNU1** [comment]
The problem also affects all the caffe installations, I don't think anybody can get it installed by following the instruction until that link is fixxed

**Comment by justas-eko** [comment]
Same issue.

**Comment by nExmond** [comment]
https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1602#issuecomment-641653411

**Comment by IBNU1** [comment]
Thank you  so much I was looking everywhere for a backup

**Comment by antoinefalisse** [comment]
@nExmond I don't think the latest versions of the 3rd party files are on the G drive:
- caffe3rdparty_16_2020_11_14
- caffe_16_2020_11_14
- opencv_450_v15_2020_11_18

I could build things with older versions, but I cannot get the examples to run (it starts and then stops responding). Could that be somehow related to me using `caffe3rdparty_15_2019_03_14` and `caffe_15_2020_04_05` instead of `caffe3rdparty_16_2020_11_14` and `caffe_16_2020_11_14`? Thanks!

**Comment by gineshidalgo99** [comment]
Updated the links in #1602, sorry about that
