### ISSUE TITLE
Maximum accuracy configuration query

### ISSUE THREAD

**Issue by shivenmian** [CMU-Perceptual-Computing-Lab/openpose#203]
@gineshidalgo99 I'm using Openpose for body pose detection on a 4k video, and have a few questions, would be great if you answered them:

1. The maximum accuracy configuration is {net_resolution 1312x736, scale_number 4 and scale_gap 0.25}. Also, it's given that net_resolution should be closest possible to aspect ratio of the input video. So what does the net_resolution in the max accuracy config work for best (i.e the vid quality). Ideally, I'd want the entire 4k quality of my input to be used by the convnet.

2. Using the max accuracy configuration makes my GPU run out of memory (it's exactly 8 GB). I reduced the scale_number to 3 and got it running, but was getting some noise (it could detect more people than default configs, but also had more erroneous detections). Would you recommend reducing the resolution or the other parameters to get the next best accuracy i.e what should affect the accuracy more?

3. You haven't really mentioned what net_resolution means in the documentation, except that increasing it increases accuracy. Is it the resolution the video frames are downscaled to before feeding into the net or something?

Unfortunately, I can't really show the videos I'm using or the Openpose output at this point because our data is classified.

### Your system configuration
**Operating system** : Ubuntu
**CUDA version**: 8.0
**cuDNN version**: 5.1.5
**GPU model** (`nvidia-smi` in Ubuntu): GeForce GTX 1080
**Caffe version**: Default from OpenPose
**OpenCV version**: installed with `apt-get install libopencv-dev` (Ubuntu)
Compiler (`gcc --version` in Ubuntu): 5.4.0

**Comment by shivenmian** [comment]
@gineshidalgo99 @tsimk could you help out?

**Comment by gineshidalgo99** [comment]
1. It depends on the scale of the people in the 4K image. I.e. if it is used instead of 1080p video, the same net would be the best. If it is used to bigger seen, then the net resolution should be increased. It depends more on the average scale of the people on the image.
2. That is always the trade off unfortunately. If you use 3 scales with 1312x736, I'd go with 0.33 as scale_gap.
3. Exactly, it is that. Sorry for not adding it to the doc. I'll add it soon.

Sorry for the huge delay.
