### ISSUE TITLE
Problem installing openpose on windows 10 using visual studio 17

### ISSUE THREAD

**Issue by arthitag** [CMU-Perceptual-Computing-Lab/openpose#211]
### Issue summary
I tried to build Openpose on Visual Studio 17. I followed all the steps of installation as provided in the doc/installation.md. 

When I try to build the project I get the following error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file '..\x64\Release\OpenPose.lib'	OpenPoseDemo		

### Executed command (if any)
Build OpenposeDemo on VS 2017

### OpenPose output (if any)
None

### Type of issue
Compilation/installation error
Help wanted

### Your system configuration
windows 10
cuda: v8.0
cuDNN version:5.1 
**Caffe version**: Default from OpenPose
**OpenCV version**:  default from OpenPose (Windows) 
Visual Studio (Windows): visual studio 17

**Comment by gineshidalgo99** [comment]
`Error	LNK1181	cannot open input file '..\x64\Release\OpenPose.lib'	OpenPoseDemo`

That means the OpenPose project could not be compiled successfully. Could you check there is no building problems when compiling only the OpenPose project? (i.e. without examples)

**Comment by philipNoonan** [comment]
I dont think cuda 8.0 works with MSVC2017. https://devtalk.nvidia.com/default/topic/997997/cuda-support-for-visual-studio-2017/ 

Perhaps trying cuda 9.0 RC, or going down to MSVC2015, might help.

**Comment by gineshidalgo99** [comment]
Caffe only works officially with VS 2013 or 2015:
https://github.com/BVLC/caffe/tree/windows

We only support 2015, but I guess VS 2013 could be done since the main problem is Caffe, the rest is just C++11 and OpenCV code.

So we cannot support any other VS until they make it work there... I'm sorry

**Comment by arthitag** [comment]
Hi. I switched to VS15 and got OPenpose to compile and run.

**Comment by gineshidalgo99** [comment]
I saw some link about how to enable CUDA 8 for VS 2017 community, we do not support it, but if you really want VS 2017, [check this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#installation---library), VS 2017 part.

**Comment by ifm1994** [comment]
Thanks but i just unninstalled all, I'll follow the steps withe the same versions hehehe ^^

**Comment by doodleyy96** [comment]
Dear Professor, dose Openpose work with V S2015  and CODA 9.0 and cuDNNv7.0.3?

**Comment by gineshidalgo99** [comment]
We have never tried it, if you do and it works, please feel free to make a pull request with the steps in how to build it with it. If it works out of the box, please just let me know so I'd include the fact that it works for CUDA 9. Thanks!

**Comment by doodleyy96** [comment]
I tried many times. Use VS2015   + CODA 9.0 + cuDNNv7.0.3 
Always the same error:
Error	LNK1181	cannot open input file '..\x64\Release\OpenPose.lib'	

I assume Openpose cannot support CUDA 9 now..
But later I will tried again.

**Comment by gineshidalgo99** [comment]
That just means that OpenPose itself (not the demos) was not properly compiled. I guess you would have to specify CUDA 9 instead of 8 somewhere (not sure if in VS or Windows or OpenPose build or where).

**Comment by doodleyy96** [comment]
Dear Professor, would you mind providing me the CUDA 8 Kit? I just going to figure out if openpose can work with CUDA 8 in my computer. now CUDA 8 Kit cannot be found on any website,.

**Comment by gineshidalgo99** [comment]
It can be downloaded from their official website... https://developer.nvidia.com/cuda-toolkit-archive

**Comment by doodleyy96** [comment]
Professor, good news, I have run the Open Pose successfully last night.
I concluded the my failures:
At first, I cannot compile the Open Pose(not the demos)-----because I use CUDA9.0 , when I turn to CUDA 8.0, it works.

Then, I cannot compile the Open Pose demos-------the problem is in the linker，there is a checkbox，when I delete the "inherit from parent or project default "option in Open Pose demos and Open Pose, it works. Because there are some redundant “.dll”.

Anyway, thank you very much!

**Comment by uvas94** [comment]
Hey. I had the same problems as the guys on this thread. I tried to run  OpenPose with Cuda 9 and Visual studio 2017 and got different problems. After reading this thread I looked in the .vcxproj and change the necessary paths from Cuda 8 to Cuda 9 and found out that it works as intended without any other change.

**Comment by gineshidalgo99** [comment]
@uvas94  Thanks for your feed-back! I've added to the doc for the next commit. Thanks

**Comment by RatsLoveCats** [comment]
I chose X64 during the build, but there will still be fatal error LNK1181: Unable to open the input file "..\..\src\openpose\Release\openpose.lib", how can I solve it?
My configuration:
Windows 10
Cuda:v9.0
cuDNN version: 9.0
Caffe version: default from OpenPose
OpenCV version: default from OpenPose (Windows)
Visual Studio (Windows): visual studio 17

**Comment by uvas94** [comment]
Did you check if you have the openpose.lib file? In my version there is no Release folder, that is why I'm asking/

**Comment by narratorxu** [comment]
I meet the same problem as yours, but I can not find where to change the necessary path from Cuda8 to Cuda9 in the .vcxproj, can you tell more details？Many thanks!

**Comment by yukun7273** [comment]
> @uvas94 I meet the same problem as yours, but I can not find where to change the necessary path from Cuda8 to Cuda9 in the .vcxproj, can you tell more details？Many thanks!

I met the same problem, have you solve the peoblem?

**Comment by narratorxu** [comment]
@yukun7273 not yet...

**Comment by uvas94** [comment]
Hi there. It's been some time since I used this, but from what i see after you build using cmake you have a windows folder and an ubuntu folder. I used the windows with vs option as the thread states. In the windows folder there are two places where I did the modification:
1.In **_.\windows\OpenPose\OpenPose.vcxproj_**
<ImportGroup Label="ExtensionSettings">
    <Import Project="$(VCTargetsPath)\BuildCustomizations\CUDA 9.0.props" />
</ImportGroup>
2. In _**.\windows\OpenPoseDemo\OpenPoseDemo.vcxproj**_
<Link>
      <EnableCOMDATFolding>true</EnableCOMDATFolding>
      <OptimizeReferences>true</OptimizeReferences>
      <AdditionalLibraryDirectories>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\lib\x64</AdditionalLibraryDirectories>
      <AdditionalDependencies>..\..\3rdparty\windows\caffe3rdparty\lib\gflags.lib;..\..\3rdparty\windows\opencv\x64\vc14\lib\opencv_world310.lib;..\x64\Release\OpenPose.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
Hope this helps. 
I would assume that this issue can be resolved by configuring the cmake to choose the newer version of cuda.

**Comment by marcborrass** [comment]
Hi, I am trying to install openpose and I am using the newest version of VS, with the C(C++ compiler included, and I get the following error in the CMake-GUI: "Error in configuration process, project files may be invalid". I have no clue how to overcome this, since I have looked for tips but I cannot solve this issue. Any idea how to solve this?
