### ISSUE TITLE
the problem of impelmenting the nmsbase.cpp

### ISSUE THREAD

**Issue by andyqian2015** [CMU-Perceptual-Computing-Lab/openpose#216]
when I try to implement the class of nmsbase.cpp  using the mode of cpu to get the spPeaksBlob。 I use the code which you has commented, but no people detect out. I add channel to the code ,the frame drop less to one. can you give me some suggestion to deal with the problem. thx.

**Comment by gineshidalgo99** [comment]
The code is commented because it is a really old version which is not completed. It needs a re-implementation, the commented code with that early implementation is to have an idea.

Right now it is far in our to-do list given the low performance it would have compared to GPU modes, but if you implement it, feel free to make a pull request. Thanks!

**Comment by gineshidalgo99** [comment]
Indeed, CPU version was already fixed and added to the CPU version of OpenPose.
