### ISSUE TITLE
How can I use OpenPose in another project?

### ISSUE THREAD

**Issue by ShihanWang** [CMU-Perceptual-Computing-Lab/openpose#22]
### Issue summary
my test project: i just copy the file rtpose.cpp to the project.Then i write a CMakeLists.txt:
CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
PROJECT(test)
SET(CMAKE_CXX_COMPILER "g++")
SET(CMAKE_BUILD_TYPE Debug)
SET(CMAKE_CXX_FLAGS "-std=c++0x")
find_package(CUDA REQUIRED)
INCLUDE_DIRECTORIES(
${CUDA_INCLUDE_DIRS}
/home/wsh/projects/openpose/include
/home/wsh/projects/openpose/3rdparty/caffe/include
)
ADD_EXECUTABLE(pose rtpose.cpp)
TARGET_LINK_LIBRARIES(pose
${CUDA_LIBS}
/home/wsh/projects/openpose/build/lib/libopenpose.so
/home/wsh/projects/openpose/3rdparty/caffe/build/lib/libcaffe.so
)
I can run the examples successfully in openpose, but in my test project, it can not. 

### Type of issue
Help wanted

### OpenPose output (if any)
/home/wsh/projects/openpose/include/openpose/experimental/face/faceExtractor.hpp:48:29: error: ‘ResizeAndMergeCaffe’ was not declared in this scope
std::shared_ptr<ResizeAndMergeCaffe> spResizeAndMergeCaffe;
/home/wsh/projects/openpose/include/openpose/experimental/face/faceExtractor.hpp:49:29: error: ‘NmsCaffe’ was not declared in this scope
std::shared_ptr<NmsCaffe> spNmsCaffe;
......

**Comment by gineshidalgo99** [comment]
This is from a Makefile file where I used the OpenPose binaries in a different project, I think you forgot to add the USE_CAFFE define in your cmake, you can get the required defines from my Makefile (there might be some duplication since I did it quickly, but it is working):

# OpenPose (assuming it is located in ./3rdparty/openpose)
`-Wl,-rpath=./3rdparty/openpose/lib -Wl,-Bdynamic -L./3rdparty/openpose/lib/ -lopenpose -DUSE_CAFFE`

# Caffe
`-Wl,-rpath=./3rdparty/caffe/lib -Wl,-Bdynamic -L./3rdparty/caffe/lib/ -lcaffe -DUSE_CUDNN`

# OpenCV
`-lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_contrib -lopencv_calib3d`
# Add more OpenCV flags if you need them

# CUDA
# Something like:
`-I/usr/local/cuda-8.0/include/ -L/usr/local/cuda-8.0/lib64 -lcudart -lcublas -lcurand`

# 3rdparty that Caffe uses
`-lcudnn -lglog -lgflags -lboost_system -lboost_filesystem -lm -lboost_thread`

# Other required
`-pthread -fPIC -std=c++11 -fopenmp`

# Optimization flags (optional)
`-DNDEBUG -O3 -march=native`

Let me know whether it works

**Comment by ShihanWang** [comment]
Thank you very much.  I have solved the problem and I found that:
1. In my CMakeLists.txt,  I need to change the Caffe directory:  SET(caffe_DIR ${OpenPose_DIR}/3rdparty/caffe/distribute);
2. I delete "#ifdef USE_CAFFE"  in some files named as xxCaffe.hpp in openpose/include/.
Then I make openpose again and everything is OK.  Without the 2nd step, I will have the same problem.But I do not know what is the effect of my change, maybe I just need to add USE_CAFFE in my CMakeLists.txt.

**Comment by gineshidalgo99** [comment]
Thank you for posting it! Closing this then.

**Comment by yorgosk** [comment]
Hello!

I am trying to use my current OpenPose installation for the compilation of another project (for the https://github.com/stevenjj/openpose_ros to be specific). I have build and tested my OpenPose installation as the documentation instructs me and everything seems fine, however I cannot do ```make distribute```. I have searched the documentation for a solution, but I am probably missing something.
Since the instructions above are about one and a half year old @gineshidalgo99 can you please give me an update?

Thanks!

**Comment by gineshidalgo99** [comment]
Hi, I believe doc/install.md has an explanation on how to include the library through CMake

You talk about `make distribute`, could you quickly send me a link to the instructions (in current master OP) where it says `make distribute`? So I can update that part.

**Comment by yorgosk** [comment]
Okay, I'll check doc/install.md again.

The instructions in current master do not mention anything about make distribute, as far as I have read them. I first read about it here and I figured that since it used to be an option but apparently it is no more, I better ask you for a pointer to the thing that you substituted it with.

**Comment by gineshidalgo99** [comment]
OK yeah, this is based on the old basic installer, the new installer way (using CMake) provides much higher configuration settings, following how big libraries do it (e.g., OpenCV, Caffe, etc.).

So please, check https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#openpose-from-other-projects-ubuntu-and-mac for all the details.

**Comment by burnzzz** [comment]
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#openpose-from-other-projects-ubuntu-and-mac  is dead link.
