### ISSUE TITLE
 Some Questions of the Multi-Threading Design Pattern

### ISSUE THREAD

**Issue by dasheyuan** [CMU-Perceptual-Computing-Lab/openpose#236]
1. `/include/openpose/Thread/enumClasses.hpp`
what's the meaning that '`first and last queues will be given to the user`'?
and `'input queue`' is the meaning that emplace/push datum in the queue?
and '`output queue`' is the meaning that pop datum from the queue?
or other meanings?

2. what is you idea to design the '`queueIn`' and '`queueOut`'?
I kown your Multi-Threading Design Pattern is `Producer/Comsumer Pattern` and the queue is a `container` of the `TDatum`,  but I am so confused to your design details of the  '`subThreadQueueInOout`'.
@
Anything significant guide paper to help me solve the puzzle?
Thanks:)

**Comment by gineshidalgo99** [comment]
@dasheyuan Sorry if it's not clear enough, I'm definitively not a pattern expert.

1. It means that if the Asynchronous mode is used, those are the queues that the user interact and push/pop to/from. `input` and `output` in which class/function? So I can answer properly. 
2. Instead of Producer/Consumer pattern, I used a variation Producer/consumer-producer/consumer. So the shared object is sent across several `Worker` classes. Producer will be related to `subThreadQueueIn` to emplace elements there, Consumer with `subThreadQueueOut` to pop them from there, the consumer-producer with `subThreadQueueInOut`.

Let me know if it's now more clear. Thanks!

**Comment by dasheyuan** [comment]
I think it's so close to the 'truth' of your design after your reply below. However, 

when I debug the code `examples/tutorial_thread/1_openpose_read_and_display.cpp` setup by setup, 
I found that `wDtaumProducer` is related to `subThreadQueueOut` while  `wGui` is related to `subThreadQueueIn`. 
In other words, `subThreadQueueOut`  initializes with parameters `wDtaumProducer` and `mTQueue[0]` ,  `subThreadQueueIn`  initializes with parameters `wGui` and `mTQueue[0]`. 

Look at this key code,
`subThradQueueIn.hpp` 
```
   bool SubThreadQueueIn<TDatums, TWorker, TQueue>::work()
    {
        try
        {
            // Pop TDatums
            TDatums tDatums;
            bool queueIsRunning = spTQueueIn->tryPop(tDatums);
            // Check queue not empty
            if (!queueIsRunning)
                queueIsRunning = spTQueueIn->isRunning();
            // Process TDatums
            const auto workersAreRunning = this->workTWorkers(tDatums, queueIsRunning);
            // Close queue input if all workers closed
            if (!workersAreRunning)
                spTQueueIn->stop();
            return workersAreRunning;
        }
```
`subThradQueueOut.hpp` 
```
 bool SubThreadQueueOut<TDatums, TWorker, TQueue>::work()
    {
        try
        {
            // If output queue is closed -> close input queue
            if (!spTQueueOut->isRunning())
                return false;
            else
            {
                // Process TDatums
                TDatums tDatums;
                const auto workersAreRunning = this->workTWorkers(tDatums, true);
                // Push/emplace tDatums if successfully processed
                if (workersAreRunning)
                {
                    if (tDatums != nullptr)
                        spTQueueOut->waitAndEmplace(tDatums);
                }
                // Close queue otherwise
                else
                    spTQueueOut->stopPusher();
                return workersAreRunning;
            }
        }
```
So, is there anything wrong between your reply below and the code?
Hope for your reply again.
:)

**Comment by gineshidalgo99** [comment]
You are right! I typed the opposite (I've just corrected)! `SubThreadQueueOut` means that at the output of that class there is a `Queue`, so that it emplaces elements to that `Queue`. `SubThreadQueueIn` means that at the input of that class there is a `Queue`, hence the class has to get (pop) elements from it.

Is it clear now? (sorry for the confusion!)

**Comment by dasheyuan** [comment]
Thanks for your patient help. It 's clear enough! 
Reading the codes of this program is a kind of  enjoyment.
