### ISSUE TITLE
Is it possible to run the library on a Tango Android device?

### ISSUE THREAD

**Issue by nigellima** [CMU-Perceptual-Computing-Lab/openpose#247]
Good morning!

I have a smartphone Lenovo Tango phab 2 which I would like to combine its depth features with OpenPose keypoints tracking. I checked CUDA's documentation and I saw that Google Procect Tango devices are compatible.
So, is it possible to use Lenovo Phab 2 to run OpenPose as it has CUDA support?

By the way, congrats for the library. It is incredible.

**Comment by ildoonet** [comment]
I think that is.. hardly possible with current implementations.

But if you build tensorflow for android, you can check my re-implementation for this repo in tensorflow, so with some modifications, you can deploy this model to your android.

https://github.com/ildoonet/tf-openpose

**Comment by Rafcin** [comment]
Tangos dead, it shuts down in March. Don't use it. Also the Phab2Pro is terrible with TF

**Comment by rajithprasath** [comment]
can anyone tell how to do this with android?

**Comment by Rafcin** [comment]
Tango is dead, unless you use the Yellowstone tablet, maybe.

On Mar 13, 2018 11:03 AM, "rajithprasath" <notifications@github.com> wrote:

can anyone tell how to do this with android?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/247#issuecomment-372762023>,
or mute the thread
