### ISSUE TITLE
Atlas/Blas/Mkl selection not available in core makefile

### ISSUE THREAD

**Issue by ul1994** [CMU-Perceptual-Computing-Lab/openpose#291]
Just wanted to note if this is an actual issue and if others ran into this. The box I use does not have atlas or openblas but has mkl, so I've been trying to compile with mkl exclusively.

I was not able to specify a choice of BLAS in `Makefile.config` in the main compilation step and after digging into the actual makefile found that the Makefile for openpose does not handle any actions for such flags (While the caffe makefile did). 

My temporary solution was to copy the BLAS option lines from the caffe makefile into the primary makefile.
Perhaps reflecting these changes to the project's makefile would be helpful to other mkl users.

**Comment by gineshidalgo99** [comment]
OpenPose does not use atlas/openblas/mkl, I mean, internally, Caffe uses it, but no other parts of OpenPose use it. That is why OpenPose does not have an option for it, only Caffe has it. So you are fine with only adding MKL to the Caffe Makefile.config, no need to modify OpenPose Makefile.config for that.

**Comment by ul1994** [comment]
I did run into an issue where `netCaffe.cpp` in openpose/core calls a caffe file - If I'm reading the output correctly, either my environment or my modifications did not allow mkl to be used at this step.

```bash
In file included from 3rdparty/caffe/distribute/include/caffe/util/math_functions.hpp:11:0,
                 from 3rdparty/caffe/distribute/include/caffe/layer.hpp:12,
                 from 3rdparty/caffe/distribute/include/caffe/net.hpp:12,
                 from src/openpose/core/netCaffe.cpp:5:
3rdparty/caffe/distribute/include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
 #include <cblas.h>
                   ^
compilation terminated.

**Comment by gineshidalgo99** [comment]
Does that happen from Makefile or CMake compilation? From CMake it should work better, but not sure in this case. Thanks!

**Comment by rajhlinux** [comment]
I'm also getting this error with Atlas when I manually built Caffe with OpenBlas.

Caffe hasn't been touched/updated for 4 years (dead officially?). The error is because OpenPose is building Caffe with the worst BLAS implementation since Caffe defaults ATLAS, however it's recommended to not use Atlas and install OpenBlas. 

Installing Atlas will take days for it to compile with CPU throttling. OpenBlas is also better optimized.

There are people also getting errors with Protobuf with Caffe since it is using a deprecated version of it.
Same goes for Python with Caffe using a deprecated version.

I think OpenPose should have their own repository or simply change the default installation dependencies on the fly for Caffe with the proper updated installations/parameters.
