### ISSUE TITLE
Each startup is slow. How can I get the body  key-points more quickly?

### ISSUE THREAD

**Issue by a2940519** [CMU-Perceptual-Computing-Lab/openpose#32]
### Issue summary
Every time I start, GUI has to keep the screen black for some time.
I just want 18 body key-points on the picture. 
How can I get the body  key-points more quickly?

Thanks.
### Executed command (if any)
./build/examples/openpose/rtpose.bin --image_dir ./data/ --write_pose_json ./output/ --num_gpu 2

### OpenPose output (if any)
Sometimes there is only one person in the picture, but it outout  2 body data??

### Type of issue
- Help wanted
- Question

### Your system configuration
**Operating system** (`lsb_release -a` on Ubuntu):
ubuntu 14.04
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
cuda 8.0
**cuDNN version**:
cudnn-8.0-linux-x64-v5.1
**GPU model** (`nvidia-smi`):
Wed May 17 10:43:18 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.48                 Driver Version: 367.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 0000:03:00.0     Off |                  N/A |
| 33%   43C    P0    39W / 180W |      0MiB /  8113MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 750     Off  | 0000:84:00.0     Off |                  N/A |
| 25%   38C    P0     1W /  38W |      0MiB /   979MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 750 Ti  Off  | 0000:85:00.0     Off |                  N/A |
| 25%   37C    P0     2W /  38W |      0MiB /  2000MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

Compiler (`gcc --version` on Ubuntu):
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

**Comment by gineshidalgo99** [comment]
Check #30

In addition, if you have 3 GPUs, use them all: `--num_gpu 3`. I assume with those 3 GPUs it should run around 9-15 fps? Please, let me know the FPS it tells you so I can check it is right.

**Comment by a2940519** [comment]
@gineshidalgo99  Thanks
But now I have the same problem
status == CUDNN_STATUS_SUCCESS (3 vs. 0) CUDNN_STATUS_BAD_PARAM
status == CUDNN_STATUS_SUCCESS (2 vs. 0) CUDNN_STATUS_BAD_PARAM
...

**Comment by gineshidalgo99** [comment]
You are using a PASCAL architecture graphics card (GTX 1080), together with a Kepler (I think) architecture (GTX 750). Since they are different architecture models, the problem might be that CUDA and/or cuDNN is only working for one kind of model, not for both.

Please, check that you can run CUDA/cuDNN programs with 2 GPUs of different category at the same time, since I am not sure. I know it works with model of the same series (e.g. 1080 and 1050, or 980 and 970). Not sure about different series (the series is indicated by all digits but the last 2: 10XX, 9XX, 8XX, etc.).

Can you run the program with each GPU independently?
`./build/examples/openpose/rtpose.bin --image_dir ./data/ --write_pose_json ./output/ --num_gpu 1 --num_gpu_start 0`
`./build/examples/openpose/rtpose.bin --image_dir ./data/ --write_pose_json ./output/ --num_gpu 1 --num_gpu_start 1`
`./build/examples/openpose/rtpose.bin --image_dir ./data/ --write_pose_json ./output/ --num_gpu 1 --num_gpu_start 2`

**Comment by a2940519** [comment]
@gineshidalgo99  Thanks.
Yes, I can run the program with each GPU independently.

**Comment by gineshidalgo99** [comment]
Then I assume is a Nvidia mismatch driver issue, not sure if there is solution for that, sorry! Post if you find any solution for it. Meanwhile I will close it since we cannot further help you.

About the best choice for you: GTX 1080 should run around 6-10 FPS while each 750 around 1-3 FPS. Use the GTX standalone, it should be faster than both 750. Post if your speed is smaller than these numbers, it should not.

About speed-up, check when we release the version 1.0.0rc3 / 1.0.0 (not sure the name yet), it will have a ~30% speed up.

**Comment by a2940519** [comment]
Thanks
