### ISSUE TITLE
Some question about openpose 3D to rewrite the pointGrey class

### ISSUE THREAD

**Issue by Zakeiswo** [CMU-Perceptual-Computing-Lab/openpose#338]
Hello, I'm a college student, and I'm new to this.
Now I want to ask some questions about the openpose3D ,I also want to use 2 playstaion3eyes to change the FLIR camera. I have seen some issues with it said I have to change the pointGrey class.However, I can't figure out how to change it.Do I have to change all the function about Spinnaker?just like this one:
`cv::Mat pointGreyToCvMat(const Spinnaker::ImagePtr &imagePtr)`
and change every function used in Spinnaker to other function which in my CL PS3 Eye Multicam SDK ?
I have downloaded the CL PS3 Eye Multicam SDK from [https://codelaboratories.com/downloads/](url)
However ,I found not all the function of this SDK have the same Features to function in Spinnaker.
Please tell me which part needs to be changed?

**Comment by nanma56** [comment]
Dear Prof, 

I have a similar question, I changed the aquireimages() in pointGrey.cpp file to read the images from 3 videos instead of three cameras. However, after compiling, the code only freeze on the first frame and not moving on. I study the openposedemo.cpp and it used a producer class to process the video, my question is in order for openPose3D to work with video, do I have to use the producer class as the openposedemo does?

Thanks

**Comment by Zakeiswo** [comment]
Hello,
I'm new to this, but have you seen the Getting frames of the function acquireImages().In this function, it gets frames from the cameras then retrieve next received image and ensure image completion. I don't the details of your code, but I think the bug might happen here.

**Comment by nanma56** [comment]
Actually, I just figured it out. The reason was when I hack the code, I added VideoReader as a local variable. So it got destroyed and recreated at every cycle. The issue is fixed by moving the Objects to the private member of the Workpointgrey class
