### ISSUE TITLE
The option --process_real_time throws an exception

### ISSUE THREAD

**Issue by dtosato** [CMU-Perceptual-Computing-Lab/openpose#35]
### Issue summary
The option --process_real_time throws an exception trying to start the demo.

### Executed command
./build/examples/openpose/openpose.bin --process_real_time

### OpenPose output
Starting pose estimation demo.
HIGHGUI ERROR: V4L2: Unable to get property <unknown property string>(5) - Invalid argument
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Error:
Selected to keep the source fps but get(CV_CAP_PROP_FPS) <= 0, i.e. the source did not set its fps property.

Coming from:
- src/openpose/producer/producer.cpp:setProducerFpsMode():71
- src/openpose/producer/producer.cpp:setProducerFpsMode():78
- ./include/openpose/wrapper/wrapper.hpp:configure():726
- ./include/openpose/wrapper/wrapper.hpp:configure():383

Aborted (core dumped)

### Type of issue
Execution error

### Your system configuration
**OpenCV version**:  2.4.9.1
**Operating system**: Ubuntu 16.04.2 LTS
**CUDA version**: 8.0.61
**cuDNN version**: 6.0.21
**GPU model**: 375.51
**Caffe version**: Default from OpenPose.
**Compiler**: 5.4.0 20160609

**Comment by gineshidalgo99** [comment]
I will change the message so it is more informative.

But the `process_real_time` option was meant for video. For webcam (as you are trying), that option is applied by default, since the webcam will automatically drop frames if the speed is too slow.

I will avoid the program to send an error with `./build/examples/openpose/openpose.bin --process_real_time` since it is actually applied by default. But meanwhile, simply use `./build/examples/openpose/openpose.bin`, it is completely equivalent for webcam.

**Comment by gineshidalgo99** [comment]
As I said, there is no practical difference for webcam in using `process_real_time` or not, but at least now it does not throw an error. Thanks for the catch.
