### ISSUE TITLE
How to run openpose as a server process which listen at a port to handle detection request

### ISSUE THREAD

**Issue by AlexLuya** [CMU-Perceptual-Computing-Lab/openpose#390]
I want to initialize an openose instance,save it as a class field,and this class implemented some grpc related logic,will listen on a port,and I want pass the request(an image) from this port to saved openpose instance for detection,then return back detection result to this port.question is:

Is this possible?
If yes,can anyone give me some demo code,thanks very much

Note,I have tried to do it with python but got an error:https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/387

**Comment by AlexLuya** [comment]
After change poseExtractor:checkThread() method to 
```
    void PoseExtractor::checkThread() const
    {
        try
        {
            if(mThreadId != std::this_thread::get_id())
				std::cout<<"poseExtractor:Error from a different thread access CPU/GPU pointer*****but Alex disabled this error for RPC mechnism*****god bless no any side effects"<<std::endl;
               // error("The CPU/GPU pointer data cannot be accessed from a different thread.",
               //      __LINE__, __FUNCTION__, __FILE__);
        }
        catch (const std::exception& e)
        {
            error(e.what(), __LINE__, __FUNCTION__, __FILE__);
        }
    }
```
Hope no side effect

**Comment by gineshidalgo99** [comment]
It might cause random core dumped in the code.

The best way to do that, it's by following the tutorial_wrapper/2_*.cpp example, implement your custom image input and output

**Comment by yxchng** [comment]
@AlexLuya Is your solution working fine? I also need this. I can't get openpose to integrate with my code, it gives "The CPU/GPU pointer data cannot be accessed from a different thread." error.

**Comment by gineshidalgo99** [comment]
@yxchng 
It has to be in the same thread than fowardPass to initialize the GPU resources, otherwise you'd have a core dumped. You should only run it once per available GPU, not 1 per image. Process all the images with the same thread for max. speed

**Comment by yxchng** [comment]
@gineshidalgo99 it is not processing videos or images, it is processing livestream, therefore it is not possible to batch all of them and run them once. It has one function call per image. Since the camera feed is not solely to be consumed by openpose, someone master node will call that function once per image.

**Comment by gineshidalgo99** [comment]
I'd say that yes, it's possible, I'd create a queue system, so the main thread (where OpenPose is processing images) simply reads and process images from that queue (and return them to their respective threads if required). All other threads simply read images and put them into that queue. Otherwise, it's a CUDA/Caffe requirement to initialize the GPU memory in the same thread where the network is gonna run, I can't do anything against this.
