### ISSUE TITLE
Number of output files

### ISSUE THREAD

**Issue by inesrd** [CMU-Perceptual-Computing-Lab/openpose#409]
Hi!

I have a question regarding the output files of OpenPose. The number of files should be the same as the number of frames of the video? Or there is a specific frequency?

Many thanks,
Ines

**Comment by gineshidalgo99** [comment]
Yes, it should be the same number.

However, sometimes, due to video codecs (with special compressed formats), some frames (specially at the beginning) might be corrupted and the software would skip them.

If you really want same #frames than #keypoint files, then you can either:
1) Also use write_images to be sure you have the same number.
2) Convert the file into a lightly processed format, such as avi.
