### ISSUE TITLE
Output heatmap size interpretation

### ISSUE THREAD

**Issue by NasGit3** [CMU-Perceptual-Computing-Lab/openpose#429]
**Issue Summary:**
I have a problem with the heatmaps output size. I get heatmaps of size 20608 by 368. But, 20608 is not divisible by 656. My original frames are of size 512 by 512, but based on your explanation [#86](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/86) images will be downsized to the deep net size which is 656 by 368.

**Executed Command:**
--part_to_show 20 -heatmaps_add_parts false -heatmaps_add_PAFs true

**Update:**
I realized that 20608 is divisible by 368. I also tried to remove _-heatmaps_add_parts false_ and this time I get heatmaps of size 13984 by 368, where 13984 is also divisible by 368. But, the height of the heatmap is also 368. Does this mean the images will be downsized into 368 by 368?
lastly, I still cannot understand the total number of heatmaps which is said to be 67 in the documentation. I understand that there are 18 keypoints + 1 background + 2*19 (number of PAFs: 19 for x-direction and 19 for y-direction) = 18 + 1 + 38 = 57. I was hoping that you can help me to figure out where does the rest of the 10 heatmaps come from?

**Comment by gineshidalgo99** [comment]
There must be 57 channels if you use the 3 `heatmaps_add_*` flags. If you use `net_resolution 656x368`, then you would be able to divide total width by 57 and get 656.

If you use the default net_resolution -1x368, then the width will be automatically estimated (check doc/demo_overview.md for details). But you can always divide your size / 57 to know your width. However, you are adding only PAFs, so there will be 38 channels total, so you should divide into 38 instead of 57 if only PAFs are enabled.

**Comment by Laubeee** [comment]
BTW the docs do still state `each of the 67 heatmaps` which seems to be wrong. Check https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/demo_overview.md#heat-maps-storing

**Comment by sherlockchou86** [comment]
> BTW the docs do still state `each of the 67 heatmaps` which seems to be wrong. Check https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/demo_overview.md#heat-maps-storing

I have the same question
