### ISSUE TITLE
Compatibility with OpenFace and DLib facial recognition

### ISSUE THREAD

**Issue by DonaldTsang** [CMU-Perceptual-Computing-Lab/openpose#463]
Is this software compatible with OpenFace and/or DLib's facial landmarks?  
Most facial landmarks only gives out 68 points and not 70 points
https://github.com/cmusatyalab/openface
https://github.com/TadasBaltrusaitis/OpenFace

**Comment by vvirag** [comment]
The two missing points are the pupils basically, otherwise the kaypoints are the same (in the same order).

The bigger problem is passing the bounding boxes from face detection: while openpose needs to have a slightly oversized bounding box for its facial landmark detection (and it does produce them that way after pose extraction), dlib and OpenFace require tight bounding boxes (typically from eyebrows to chin, ear-to-ear).

**Comment by gineshidalgo99** [comment]
OpenPose provides the pupils (the last 2 keypoints), that's why it has 2 more.
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md#face-output-format. Other than that, it has exactly the same keypoints.
