### ISSUE TITLE
Compilation error on Ubuntu 17.10 with both gcc 5 and 6

### ISSUE THREAD

**Issue by vutiqibyl** [CMU-Perceptual-Computing-Lab/openpose#519]
Greetings,

### Issue Summary
I tried compiling openpose with 2 versions of gcc, using cmake with the default CMakeLists.txt.
Using gcc 6.4 outputs errors such as :
    
    /usr/include/c++/6/tuple:483:67: error: mismatched argument pack lengths while expanding ‘std::is_constructible<_Elements, _UElements&&>’
    return __and_<is_constructible<_Elements, _UElements&&>...>::value;    
The whole output being available here: [output_gcc-6.4.txt](https://github.com/CMU-Perceptual-Computing-Lab/openpose/files/1871644/output_gcc-6.4.txt)
Using gcc 5.4.1 outputs :

    openpose/src/openpose/net/resizeAndMergeBase.cu(73): error: namespace "std" has no member "to_string"`

Which can be fixed by adding `-std=c++11` to CMAKE_CXX_FLAGS and CMAKE_EXE_LINKER_FLAGS, but then it causes :

    nvcc fatal   : redefinition of argument 'std'
    CMake Error at openpose_hand_generated_renderHand.cu.o.cmake:222

And the same error for other .cu.o.cmake files : [output_gcc-5.4.1.txt](https://github.com/CMU-Perceptual-Computing-Lab/openpose/files/1871737/output_gcc-5.4.1.txt)

How can I solve this problem ?

### System Configuration
**Operating system**: Ubuntu 17.10
**Installation mode**: CMake
**CUDA version**: 9.0.176
**cuDNN version**: 7.1.1
**CMake version**: 3.9.1
**Release or Debug mode**? Release
**3-D Reconstruction module added**? no
**GPU model**: GTX 980Ti 6GB
**Caffe version**: Default from OpenPose
**OpenCV version**: pre-compiled `apt-get install libopencv-dev` (3.1)
**Compiler**:  gcc 5.4.1, 6.4.0
### Type of Issue
- Compilation/installation error

**Comment by gineshidalgo99** [comment]
*.cu files are CUDA files, so the error is coming from CUDA, I'm afraid we can't give you much support from there. We also recommend CUDA 8.

**Comment by davclark** [comment]
This problem stems from a regression in gcc-5 in 17.10. Ubuntu apparently won't fix it. A more comprehensive discussion of approximately the same problem is on the pytorch and caffe2 issue trackers:

- https://github.com/pytorch/pytorch/issues/5136
- https://github.com/caffe2/caffe2/issues/1633

I've made it as far as trying gcc-4.8, which also doesn't work. But no success yet.

FWIW, I'm trying to build against the standard caffe package available since 17.04 (which is built against CUDA 8), but compiling the 3rd party openpose version of course is also hit with this compiler problem.

Probably CUDA 9 is the "right way" to solve this, as gcc-5 is abandonware on ubuntu 17.10, and CUDA 9 will work with later versions of gcc. But I'll be happy to get a total hack so long as it works. If I had the option, I'd probably downgrade to 17.04, but the machine I'm working on is in Japan...

**Comment by davclark** [comment]
Confirmed: nvidia-docker on Ubuntu 18.04 is a viable path to openpose if you're already at 17.10.
