### ISSUE TITLE
Windows OpenPoseDemo.exe error

### ISSUE THREAD

**Issue by bosper131** [CMU-Perceptual-Computing-Lab/openpose#523]
Hi,

I installed the whole program according to the instructions (the configuration in CMAKE was done) and when I want to run the demo I have an error that there is no such file as DemoPose.exe. 

Does anyone know what might be the reason why this exe is not created?

**Comment by bosper131** [comment]
I meant obviously OpenPoseDemo.exe :)

**Comment by vminard** [comment]
Hi,
Did you _**build**_ also ? CMAKE is just the first step, in order to get the .exe, you need to build it. (see the next section in the instructions...).
If you don't want to build it, download the executable directly from the release section : https://github.com/CMU-Perceptual-Computing-Lab/openpose/releases
