### ISSUE TITLE
CUDNN_STATUS_SUCCESS (6 vs. 0)  CUDNN_STATUS_ARCH_MISMATCH

### ISSUE THREAD

**Issue by breeezy96** [CMU-Perceptual-Computing-Lab/openpose#524]
I followed all the steps that the "Installation" said, but the following error occured:

Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)
F0406 20:11:35.007386  6912 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (6 vs. 0)  CUDNN_STATUS_ARCH_MISMATCH
*** Check failure stack trace: ***

I installed CMake GUI, CUDA 8, cuDNN 5.1, Microsoft Visual Studio (VS) 2015 Enterprise Update 3 and everything... Same error with the Portable Version. 

And some .dll errors when I try to run from cmd: gflags.dll, glog.dll, caffe.dll, opencv_world310.dll

Anyone can help me?

**Comment by marianasilveira** [comment]
Hi, I am having the same problem.
To be more precise, the following error occurred:

F0412 09:52:30.660492  2811 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (6 vs. 0)  CUDNN_STATUS_ARCH_MISMATCH
*** Check failure stack trace: ***
    @     0x7fcaf2f805cd  google::LogMessage::Fail()
    @     0x7fcaf2f82433  google::LogMessage::SendToLog()
    @     0x7fcaf2f8015b  google::LogMessage::Flush()
    @     0x7fcaf2f82e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fcaf29d29cb  caffe::CuDNNConvolutionLayer<>::LayerSetUp()
    @     0x7fcaf29b5cfc  caffe::Net<>::Init()
    @     0x7fcaf29b8dd0  caffe::Net<>::Net()
    @     0x7fcaf489d64f  op::NetCaffe::initializationOnThread()
    @     0x7fcaf4725204  op::addCaffeNetOnThread()
    @     0x7fcaf4725b24  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7fcaf47211d4  op::PoseExtractor::initializationOnThread()
    @     0x7fcaf471dc4e  op::WPoseExtractor<>::initializationOnThread()
    @     0x7fcaf486c81c  op::SubThread<>::initializationOnThread()
    @     0x7fcaf486ea2b  op::Thread<>::initializationOnThread()
    @     0x7fcaf486ec7d  op::Thread<>::threadFunction()
    @     0x7fcaf4887a45  std::_Mem_fn_base<>::operator()<>()
    @     0x7fcaf48879d9  _ZNSt12_Bind_simpleIFSt7_Mem_fnIMN2op6ThreadISt10shared_ptrISt6vectorINS1_5DatumESaIS5_EEES3_INS1_6WorkerIS8_EEEEEFvvEEPSC_EE9_M_invokeIJLm0EEEEvSt12_Index_tupleIJXspT_EEE
    @     0x7fcaf488778a  std::_Bind_simple<>::operator()()
    @     0x7fcaf488755a  std::thread::_Impl<>::_M_run()
    @     0x7fcaf3e65c80  (unknown)
    @     0x7fcaf35b76ba  start_thread
    @     0x7fcaf38d441d  clone
    @              (nil)  (unknown)
Aborted (core dumped)

My system Configuration:
Operating system: Ubuntu 16.04
Installation mode: CMake, sh script
CUDA version: 8.0.61
cuDNN version: 6.0
GPU model: GeForce GTX 580 
Caffe version: Default from OpenPose
OpenCV version: Pre-compiled apt-get install libopencv-dev
Compiler: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 

First, I used cuDNN 5.1.10 and had a similar problem. Now I'm using version 6, since people related the problem in another topic and proposed changing the cuDNN version as a solution. In my case, didn't work. Thanks!

**Comment by gineshidalgo99** [comment]
Hi. As that GPU is quite old (series 5), I am not sure which architecture it has. I'd recommend checking which arch model it is (Fermi, Kepler, Maxwell, ...?) and making sure that a basic Caffe example works there before installing OpenPose. As this is not an OpenPose issue, but a 3rd_party one, I can't help much more. Best
