### ISSUE TITLE
Can openpose run by FPGA

### ISSUE THREAD

**Issue by geekwhy** [CMU-Perceptual-Computing-Lab/openpose#566]
I want to run openpose in FPGA，do you have API for it，or have you thought about it？

**Comment by yuanyuanli85** [comment]
If you are using Altera fpga, you can try to use [Intel's inference engine SDK](https://software.intel.com/en-us/cvsdk-fpga-support-limitations-of-the-fpga-support-for-cnn) to accelerate CNN.  But, there are lots of work ahead to run whole Openpose with it.  Good luck!  Since FPGA is not accessible to everyone, I don't believe openpose community should put much bandwidth on FPGA support.

**Comment by soulslicer** [comment]
There is an OpenCL version for OpenPose available that support OpenCL 1.2 and above. We would love it if you can try to make that work

**Comment by geekwhy** [comment]
W are trying to use Altera fpga with OpenCL, Thanks for your reply

2018-05-22 1:01 GMT+08:00 Raaj <notifications@github.com>:
