### ISSUE TITLE
Can you give me some advice?

### ISSUE THREAD

**Issue by a2940519** [CMU-Perceptual-Computing-Lab/openpose#6]
I want to do a body posture recognition, such as running, lying, etc., how can I judge these actions, can give me some suggestions?
Thanks.

**Comment by gineshidalgo99** [comment]
I guess you could start training with the 18 body key-points. If the accuracy is too low, maybe the heat maps or Part Affinity Fields (PAFs) might improve it. Otherwise taking the pixels corresponding to boundary regions to the key-points, etc. If you are using video, concatenating the body location with the existing methods, etc. 
We would like to hear your results and what it did work, so everyone can comment and learn from it. Thanks!

**Comment by a2940519** [comment]
OK 
Thank you

**Comment by wxw420** [comment]
@a2940519  Hi,Did you realize your idea? Now, I  want to recognition activity, can you can give me some suggestions?
