### ISSUE TITLE
Human Position Estimation

### ISSUE THREAD

**Issue by pmuvva** [CMU-Perceptual-Computing-Lab/openpose#644]
Is it possible to predict human position like Standing,Sitting,Walking...etc by using this stack?

**Comment by Omegastick** [comment]
It's very useful for that, but you'll have to build your own classifier on top of the Openpos output.

**Comment by pmuvva** [comment]
I am new to this area. Can you give me some reference or approach how to solve this problem?

**Comment by srikanthmalla** [comment]
@pmuvva I think you could use angle between joints to classify standing and sitting. For walking you could find if your camera is static by finding the motion of the joints.

**Comment by Omegastick** [comment]
@pmuvva I've recently implented a system for detecting whether people are sitting or standing using OpenPose. I used the Coco dataset and ran every image through OpenPose to generate my training dataset. The labels were a binary value consisting of whether the word "sitting" was in the pose label in Coco. After that, a pretty standard MLP worked wonderfully as a classifier.

Results were good, it worked nicely. I can imagine a similar thing would work for more than just 2 poses.

**Comment by priyakansal** [comment]
@Omegastick 
I am also trying to recognize action using open pose. Please guide me how you use coco data set to build the new data set and how to create the annotations (label) which I guess include the coordinates and action performed in the image.

**Comment by Omegastick** [comment]
So, I made a simple Python script that loads the labels into memory and then iterates through them and generates a list of 1s and 0s (1 for sitting, 0 for standing). These were my labels, but you could use more numbers for more actions. I then ran every image through OpenPose and save the outputs in another file, which became my training data. Then it was a simple matter of training a classifier on the data.

**Comment by priyakansal** [comment]
@Omegastick 
Got the labelling part but still not getting the procedure to generate the train data. Two points of confusion:
1) have you taken full coco dataset? if yes, then it would have taken a lot of time to extract the feature through open pose. How you handled that?
2) since the coco dataset is segmentation dataset, and images also have a boundary on the object. Is this boundary affect the training?
Please guide me on the same. Which code file of open pose repository you used to generate the output and save that. It would be great if you can dhare some of your code snippet with me . My mail id is priyagoel0211@gmail.
More over, if we are training our model to recognize action in realtime , would this approach work we’ll ?

**Comment by Omegastick** [comment]
@priyakansal
Yeah, it took a few hours to process the whole thing IIRC.

I didn't use the segmentation data at all, just ignored it. 

Sorry, all the code is owned by my work so I can't share any. None of it was very hard though, the hardest part was getting images from the camera in the end.

This runs at about 3fps on a

**Comment by priyakansal** [comment]
@Omegastick
 Thanks for the prompt response. I can totally understand your concern on sharing your work. I will try to generate the training data as suggested by you. Thanks again

**Comment by Zzoey** [comment]
@Omegastick I am just wondering if you can share any documentation/code only for research purposes under a licence. I am sure it will be helpful to many.

**Comment by Omegastick** [comment]
@ZZoey Sorry, my employer is quite strict about sharing code and doesn't allow it except under exceptional circumstances.
