### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by MJUSER** [CMU-Perceptual-Computing-Lab/openpose#657]
### Issue Summary
**openpose build issue**
_### make -j`nproc`
### Type of Issue
Build issue
[ 12%] Performing configure step for 'openpose_caffe'
CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:46 (include)

CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:46 (include)

CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:46 (include)

CMake Error at /usr/share/cmake-3.5/Modules/FindBoost.cmake:1677 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:46 (include)_

_CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/mj/Desktop/test/openpose/3rdparty/caffe/src/caffe/Boost_INCLUDE_DIR
   used as include directory in directory /home/mj/Desktop/test/openpose/3rdparty/caffe/src/caffe_

### Your System Configuration
1. **OpenPose version**: Latest GitHub code
2. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system** (`16.04` in Ubuntu):
    - **Release or Debug mode**? (by defualt: release):
    - Compiler (`gcc --version` in Ubuntu 
3. **Non-default settings**:
    4. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** (`cmake --3.5.1` in Ubuntu):
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu)
5. If **GPU mode** issue:
    - **CUDA version** (`8.0):
    - **cuDNN version**:5.1
    - **GPU model** (nvidia 830M):

**Comment by MJUSER** [comment]
This issue comes while am goin with gpu version.
Actually my system cannot support Cudnn. Is there any options to implement
openpose in my system?

Let me know is there any option like avoiding cudnn, or completly
implementjng cpu based???
can u help me sir?

This is important for my project purpose. i have gone through several
libraries. But i fond this one so helpful. But i really dont find any
helpful tutorials based on this.

I am expecting Helpz.

**Comment by FengHu1** [comment]
I have the same quetion with you.Have you solve this problem? Could you please tell me how to deal with.

**Comment by FengHu1** [comment]
[ 12%] Performing configure step for 'openpose_caffe'
CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:5 (find_package)
  CMakeLists.txt:55 (include)


CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:5 (find_package)
  CMakeLists.txt:55 (include)


CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:5 (find_package)
  CMakeLists.txt:55 (include)


CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:5 (find_package)
  CMakeLists.txt:55 (include)


CMake Error at /usr/share/cmake-3.5/Modules/FindBoost.cmake:1677 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:5 (find_package)
  CMakeLists.txt:55 (include)


-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- -- CUDA is disabled. Building without it...
-- Machine Learning Scaling Library (MLSL) found (/home/hu/桌面/openpose/3rdparty/caffe/./external/mlsl/l_mlsl_2018.1.005//intel64)
-- Forward overlapping optimization is enabled!
weight grad compression is disabled because intel compiler is not found
-- Found Atlas (include: /usr/include, library: /usr/lib/libatlas.so)
-- MKLDNN download is enabled by customized setting!
-- MKLDNN will be downloaded from github and installed in /home/hu/桌面/openpose/build/caffe
-- MKLDNN include directory: /home/hu/桌面/openpose/build/caffe/include
-- MKLDNN engine will be used as a default engine
-- Python interface is disabled or not all required dependencies found. Building without it...
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version                 :   1.0.0
--   Git                     :   unknown
--   System                  :   Linux
--   C++ compiler            :   /usr/bin/c++
--   Release CXX flags       :   -O3 -DNDEBUG -D_FORTIFY_SOURCE=2 -DMKLDNN_SUPPORTED -std=c++11 -DUSE_MKLDNN_AS_DEFAULT_ENGINE -fPIE -fstack-protector-strong -DENABLE_SGD_FUSION -fPIC -fno-operator-names -Wformat -Wformat-security -Wall -std=c++11 -Werror -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags         :   -g -DMKLDNN_SUPPORTED -std=c++11 -DUSE_MKLDNN_AS_DEFAULT_ENGINE -fPIE -fstack-protector-strong -DENABLE_SGD_FUSION -fPIC -fno-operator-names -Wformat -Wformat-security -Wall -std=c++11 -Werror -Wno-sign-compare -Wno-uninitialized
--   Build type              :   Release
-- 
--   BUILD_SHARED_LIBS       :   on
--   BUILD_python            :   OFF
--   BUILD_matlab            :   OFF
--   BUILD_docs              :   OFF
--   CPU_ONLY                :   ON
--   USE_OPENMP              :   OFF
--   USE_OPENCV              :   OFF
--   USE_LEVELDB             :   OFF
--   USE_LMDB                :   OFF
--   ALLOW_LMDB_NOLOCK       :   OFF
--   USE_SYSTEMTAP           :   OFF
--   PERFORMANCE_MONITORING  :   OFF
--   CO_SIM  :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   MKLDNN_SUPPORTED :    ON, is a default engine
--   Boost             :   Yes (ver. .)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.6.1)
--   CUDA              :   No
-- 
-- Install:
--   Install path      :   /home/hu/桌面/openpose/build/caffe
-- 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/gmock
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/gmock
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/gmock
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/gmock
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/gmock
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/gmock
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/gmock
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/gtest
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/gtest
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/gtest
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/gtest
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/gtest
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/gtest
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/gtest
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/caffe
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/caffe
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/caffe
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/caffe
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/caffe
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/caffe
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/caffe
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/caffe
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/caffe/test
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/caffe/test
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/caffe/test
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/caffe/test
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/caffe/test
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/caffe/test
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/caffe/test
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/src/caffe/test
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/tools
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/examples
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/examples
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/examples
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/examples
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/examples
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/examples
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/examples
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/examples
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/examples
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/examples
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/examples
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/examples
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/python
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/python
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/python
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/python
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/python
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/python
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/matlab
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/matlab
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/matlab
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/matlab
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/matlab
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/matlab
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/docs
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/docs
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/docs
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/docs
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/docs
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/docs
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/scripts/SystemTap
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/scripts/SystemTap
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/scripts/SystemTap
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/scripts/SystemTap
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/scripts/SystemTap
   used as include directory in directory /home/hu/桌面/openpose/3rdparty/caffe/scripts/SystemTap

-- Configuring incomplete, errors occurred!
See also "/home/hu/桌面/openpose/build/caffe/src/openpose_caffe-build/CMakeFiles/CMakeOutput.log".
See also "/home/hu/桌面/openpose/build/caffe/src/openpose_caffe-build/CMakeFiles/CMakeError.log".
CMakeFiles/openpose_caffe.dir/build.make:105: recipe for target 'caffe/src/openpose_caffe-stamp/openpose_caffe-configure' failed
make[2]: *** [caffe/src/openpose_caffe-stamp/openpose_caffe-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/openpose_caffe.dir/all' failed
make[1]: *** [CMakeFiles/openpose_caffe.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by MJUSER** [comment]
Hai,
Yah i got it right. forget about the cpu version, and only implement the
cpu version. it works. Though it would consume  some time ,
i mean more than the usual gpu does.

**Comment by MJUSER** [comment]
srry froget about the gpu version
