### ISSUE TITLE
ERROR:Empty frame detected

### ISSUE THREAD

**Issue by taxuezcy** [CMU-Perceptual-Computing-Lab/openpose#696]
@vrichter @ps2 @loretoparisi @padeler @Derf00  ,when i run the demo for video ,i get the error 'empty frame detected,frame number 77 of 78', can anybody fix it?

**Comment by gineshidalgo99** [comment]
That's a codec issue between OpenCV and the video. It is not an error, but rather a warning (but yeah OpenCV outputs that message saying it's an error). You can ignore it.

If you really wanna solve it, just turn the video into *.avi format.

**Comment by taxuezcy** [comment]
the video is already *.avi format, i cannot ignore this problem because it stops the program @gineshidalgo99

**Comment by gineshidalgo99** [comment]
It doesn't stop for that error, it stops because it reaches the last frame (frame 77/78), which it can't read, but it exists because it reaches the last frame (even though it can't read it). Turning the video into frames is another option. We use OpenCV to read the videos, the problem is coming from that library. If you really need to solve it and my options don't work for you, the best way to look for a solution for this error is directly looking in OpenCV forums. Feel free to post the solution if you find it. Thanks!

**Comment by MLsmaller** [comment]
May I ask if you have solved this problem now? I also met this problem.
The problem is :
Empty frame detected, frame number 751 of 752. In /home/cy/openpose/src/openpose/producer/producer.cpp:checkFrameIntegrity():179
And the output video is the same as the original video

**Comment by MLsmaller** [comment]
I look forward to receiving your reply. Thank you!

**Comment by gineshidalgo99** [comment]
That's a codec problem. We internally use OpenCV to read the videos. Empty frame 751/752 means that you might be losing the very last frame due to this codec problem, but other than that, everything else is fine.
If you must have absolutely all frames, the easiest fix is turning the video into images

**Comment by taxuezcy** [comment]
@MLsmaller ,hello, i have solved this problem, i changed the file(visualization.py) in FFmpeg for 296 line,just repalced the self.inputframenum with self.inputframenum-1.By the way,it is not the best way to solve this problem. but it works

**Comment by MLsmaller** [comment]
> That's a codec problem. We internally use OpenCV to read the videos. Empty frame 751/752 means that you might be losing the very last frame due to this codec problem, but other than that, everything else is fine.
> If you must have absolutely all frames, the easiest fix is turning the video into images

Thank you for you answer,i will try it next,converting video to images does seem like a solution.

**Comment by MLsmaller** [comment]
> @MLsmaller ,hello, i have solved this problem, i changed the file(visualization.py) in FFmpeg for 296 line,just repalced the self.inputframenum with self.inputframenum-1.By the way,it is not the best way to solve this problem. but it works
That sounds good. We both have the same problem. I'm glad you've solved it.Thank you for providing this solution, and I will try to change the code later.
This is a project assigned by my tutor. I hope you can answer my questions if I am still confused.
Good luck for you.
