### ISSUE TITLE
Mode to use only every Nth frame

### ISSUE THREAD

**Issue by rogerhcheng** [CMU-Perceptual-Computing-Lab/openpose#754]
It would be useful to me (and other people) if there was a mode that used every Nth frame of the input video.  This would potentially speed things up by a factor of N, at the expense of analyzing fewer frames.  Would this be easy to implement?

**Comment by gineshidalgo99** [comment]
This is really specific, so I won't be implementing this a priority. However, I wanna warn that reading only every n frames makes video reading really slow l, because of the video codecs that compress images based on the previous one. You also have the processing_real _time flag that skip frames trying to speed up, but it's not every n frames, it's variable.

**Comment by gineshidalgo99** [comment]
This functionality has been added in the latest commit. Thanks.

(Sorry for the delay)

**Comment by yorgosk** [comment]
Hello,

I am working on a ROS wrapper for the current version of OpenPose and, because I want OpenPose to operate real-time, I try to reduce the latency as much as possible. I have a question about an OpenPose technical detail that I think I should take into account during my wrapper's operation.

How is OpenPose using the frames of a real-time video in order to decide the skeletons of the humans present to it? For instance, does it take single frames as fast as possible, which may mean that it drops certain frames while processing others, or does it take a "window" of them e.g. frames 0..29, 30..59, 60..89 etc / frames 0..29, 2..30, 3..31, etc. From what I have read so far and because of flags like ```--frame step``` I tend to believe that it does the former, taking single frames. However, I want to be sure that I fully understand this detail, because it may create opportunities for further speed improvements for my wrapper. As an extension to this question, what is the efficiency with which OpenPose can handle a stream of images relatively connected with each other vs a video?

If there is any published paper that addresses some of the above technical aspects I would also like to know.

Finally, because in older issue responses I have read that it is expected hand keypoint detection to noticeably slow down a real-time pose estimation process, can I still expect this to be the case? At least, this is what I observe while running OpenPose. 

Thanks in advance!
