### ISSUE TITLE
Performance Issue : Rapid switching between left and right bodyparts

### ISSUE THREAD

**Issue by karttikeya** [CMU-Perceptual-Computing-Lab/openpose#77]
### Issue summary
In the scenario when a pedestrian is moving perpendicular to the camera direction, OpenPose frequently confuses between the left and right body parts detection, switching between them frequently. So, for example, it would detect the knee as right in one frame and the same knee as left two/three frames later. 

I suppose, this can be improved using temporal information in the video or optical flow estimation of the target's movement. Is there some functionality I'm overlooking or any suggestions? 

### Type of issue
- Help wanted
- Enhancement / offering possible extensions

**Comment by gineshidalgo99** [comment]
Hi, that can be possible. Since we are only doing frame by frame detection (no tracking), that might happen.

So far we are not planning in incorporating any tracking in a short term, we are still trying to improve the detection as much as possible and add the next parts (face, hands, ...).

There are some methods for tracking, in case you are interested. You can take a look to #15.

Thanks!
