### ISSUE TITLE
OpenPose + Unity

### ISSUE THREAD

**Issue by IgorPereira** [CMU-Perceptual-Computing-Lab/openpose#850]
Hello,

Recently there's been a few entries on adding Unity support for OpenPose, and I'd like to know more about it.
So, is there any documentation about how to use it properly, or anything about the integration?
I've read through the docs a few times, and all I found was a notice on the changelog.

Thanks!

**Comment by gineshidalgo99** [comment]
Hi, That's a work-in-progress. Hopefully we should try to release an initial version within 1-2 months (that's why you might see some commits with that naming), but **disclaimer**, this time is not fixed and it could also be delayed a lot.

So check the latest features section in the OpenPose README (i.e. main GitHub page), as any new addition to OP would appear there as soon as it's out!

Best

**Comment by IgorPereira** [comment]
Hi!
Thanks for the quick response!

And great, I'll make sure keep looking at any changes, and good luck!
