### ISSUE TITLE
int should be replace with float in poseTriangulation.cpp

### ISSUE THREAD

**Issue by pixelite1201** [CMU-Perceptual-Computing-Lab/openpose#980]
Following line in poseTriangulation.cpp is using 1310720 in  denominator. 

`const auto imageRatio = std::sqrt(imageSizes[0].x * imageSizes[0].y / 1310720);`

This means if the image size is less than 1280*1024 dimension, imageRatio will be 0 and it will always throw following message without generating 3d points

`Unusual high re-projection error (averaged over #keypoints) of value 4.392997 pixels, while the average for a good OpenPose detection from 4 cameras is about 2-3 pixels. It might be simply a wrong OpenPose detection. If this message appears very frequently, your calibration parameters might be wrong.` 

If the denominator is changed to float value i.e. 1310720.0 it works. But, I think this should be fix with a better logic instead of providing constant value in denominator.

**Comment by gineshidalgo99** [comment]
Thanks! Fixed in the latest commit!

About better logic, this logic is actually quite robust, as it adapts the threshold depending on the image area. And that threshold grows linearly with the image width and height (rather than quadratic or any other way). Still, I am always open to hear other better/more robust ways if you think of any!
